springwolf/springwolf-core

- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/RabbitChannelsScanner.java
- springwolf-plugins/springwolf-amqp-plugin/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/RabbitChannelsScannerTest.java
according to the documentation bindings and queues are mutually exclusive so the list will contain the one that was decalred.
> IndexOutOfBoundsException when using bindings instead of queues #38

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/DefaultAsyncApiSerializerService.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/AbstractChannelScanner.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/ProducerChannelScanner.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/serializers/KafkaChannelBindingSerializer.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/ProducerData.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/DefaultAsyncApiServiceTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/AbstractChannelScannerTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/ProducerChannelScannerTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/TestChannelScanner.java
- springwolf-examples/springwolf-amqp-example/src/main/java/io/github/stavshamir/springwolf/example/configuration/AsyncApiConfiguration.java
- springwolf-examples/springwolf-amqp-example/src/main/java/io/github/stavshamir/springwolf/example/configuration/RabbitConfiguration.java
- springwolf-examples/springwolf-amqp-example/src/main/java/io/github/stavshamir/springwolf/example/consumers/ExampleConsumer.java
- springwolf-examples/springwolf-amqp-example/src/test/resources/asyncapi.json
- springwolf-examples/springwolf-kafka-example/src/main/java/io/github/stavshamir/springwolf/example/configuration/AsyncApiConfiguration.java
- springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.json
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/RabbitChannelsScanner.java
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/stavshamir/springwolf/producer/SpringwolfAmqpProducer.java
- springwolf-plugins/springwolf-amqp-plugin/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/RabbitChannelsScannerTest.java
- springwolf-plugins/springwolf-amqp-plugin/src/test/java/io/github/stavshamir/springwolf/producer/SpringwolfAmqpProducerTest.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/ClassLevelKafkaListenerScanner.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/MethodLevelKafkaListenerScanner.java
- springwolf-plugins/springwolf-kafka-plugin/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/ClassLevelKafkaListenerScannerTest.java
- springwolf-plugins/springwolf-kafka-plugin/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/MethodLevelKafkaListenerScannerTest.java
> Add ability to describe exchange and routing key for AMQP consumer and producer

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/ConsumerChannelScanner.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/ConsumerData.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/configuration/AsyncApiDocket.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/DefaultAsyncApiServiceTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/ConsumerChannelScannerTest.java
- springwolf-examples/springwolf-amqp-example/src/main/java/io/github/stavshamir/springwolf/example/configuration/AsyncApiConfiguration.java
- springwolf-examples/springwolf-amqp-example/src/test/resources/asyncapi.json
- springwolf-examples/springwolf-kafka-example/src/main/java/io/github/stavshamir/springwolf/example/configuration/AsyncApiConfiguration.java
- springwolf-examples/springwolf-kafka-example/src/main/java/io/github/stavshamir/springwolf/example/configuration/KafkaConfiguration.java
- springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.json
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/AmqpConsumerData.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/KafkaConsumerData.java
Adds new ConsumerData classes for amqp and kafka.
allows for manual definition of the consumers using new ConsumerData classes.
> Allow for manual consumer definition.

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/ConsumerChannelScanner.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/ProducerChannelScanner.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/ConsumerData.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/ProducerData.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/channel/operation/message/Message.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/DefaultAsyncApiServiceTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/ConsumerChannelScannerTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/ProducerChannelScannerTest.java
- springwolf-examples/springwolf-amqp-example/src/main/java/io/github/stavshamir/springwolf/example/configuration/AsyncApiConfiguration.java
- springwolf-examples/springwolf-amqp-example/src/test/resources/asyncapi.json
- springwolf-examples/springwolf-kafka-example/src/main/java/io/github/stavshamir/springwolf/example/configuration/AsyncApiConfiguration.java
- springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.json
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/AmqpConsumerData.java
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/AmqpProducerData.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/KafkaConsumerData.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/KafkaProducerData.java
Allow to set a optional description on the async api message object
spec: https://www.asyncapi.com/docs/reference/specification/v2.0.0#messageObject
Demo code for kafka and amqp examples was added as well
Related change in springwolf-ui will follow
> Add optional message description for manual consumer/producer definition

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/DefaultChannelsService.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/DefaultChannelsServiceTest.java
As mentioned in GH-83, only one channelItem is part of the final map - although both channelItems are found.
This improves the situation by merging the different operations for the same topic name into the same ChannelItem - while still the last one wins. This might require further improvement in the future.
> GH-83: fix: Merge operations when repeated ChannelItem found

- springwolf-examples/springwolf-kafka-example/build.gradle
- springwolf-examples/springwolf-kafka-example/src/main/java/io/github/stavshamir/springwolf/example/dtos/AnotherPayloadDto.java
- springwolf-examples/springwolf-kafka-example/src/main/java/io/github/stavshamir/springwolf/example/dtos/ExamplePayloadDto.java
- springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.json
This adds the same schema annotations + dependency as in springwolf-amqp-example
Relates to: https://github.com/springwolf/springwolf-core/issues/35
Relates to: https://github.com/springwolf/springwolf-core/pull/66
> feat: Use swagger Schema annotation in springwolf-kafka-example

- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/SpringwolfKafkaController.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/dtos/KafkaMessageDto.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/configuration/SpringwolfKafkaProducerConfiguration.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/configuration/SpringwolfKafkaTemplateFactory.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/producer/SpringwolfKafkaProducer.java
- springwolf-plugins/springwolf-kafka-plugin/src/test/java/io/github/stavshamir/springwolf/asyncapi/SpringwolfKafkaControllerTest.java
- springwolf-plugins/springwolf-kafka-plugin/src/test/java/io/github/stavshamir/springwolf/configuration/SpringwolfKafkaTemplateFactoryTest.java
- springwolf-plugins/springwolf-kafka-plugin/src/test/java/io/github/stavshamir/springwolf/producer/SpringwolfKafkaProducerTest.java
This PR should be a starting point and base for discussion to implement https://github.com/springwolf/springwolf-core/issues/51
The SpringwolfKafkaController now expects a structred request body, that contains a payload field and an optional header field to pass the kafka headers. The headers and the payload will be converted into a ProducerRecord and then passed on to the configured KafkaTemplate. I also considers the other two obvious options (http headers, query parameters) but somehow felt that this solution might be the most straight forward.
I also changed how SpringWolfKafkaProducer and its KafkaTemplate work together to improve testability and keep the KafkaTemplate out of an applications spring context.
> Extend publishing api for kafka plugin to support publishing of kafka headers

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/DefaultAsyncApiSerializerService.java
Setter is required to update the objectmapper
Use-Case: In kotlin, additional jackson modules should be registered to support all types
> Allow customization of objectMapper

- .github/workflows/springwolf-amqp.yml
- .github/workflows/springwolf-cloud-stream.yml
- .github/workflows/springwolf-kafka.yml
Avoid gh action that builds the spectral docker container first
Relates to https://github.com/stoplightio/spectral-action/issues/452#issuecomment-1285886971
> chore: Run spectral from docker container directly

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/ChannelPriority.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncListener.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncListenerAnnotationScanner.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncPublisher.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/OperationBindingProcessor.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncListenerAnnotationScannerTest.java
- springwolf-examples/springwolf-amqp-example/src/main/java/io/github/stavshamir/springwolf/example/configuration/AsyncApiConfiguration.java
- springwolf-examples/springwolf-cloud-stream-example/src/main/java/io/github/stavshamir/springwolf/example/configuration/AsyncApiConfiguration.java
- springwolf-examples/springwolf-kafka-example/src/main/java/io/github/stavshamir/springwolf/example/configuration/AsyncApiConfiguration.java
- springwolf-examples/springwolf-kafka-example/src/main/java/io/github/stavshamir/springwolf/example/consumers/ExampleClassLevelKafkaListener.java
- springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.json
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AmqpAsyncOperationBinding.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/KafkaAsyncOperationBinding.java
Follows the naming of spring (listeners and publisher) Intention is to avoid confusion with the reversed naming in asyncApi, where
- AsyncApi Publisher = Spring Listener
- AsyncApi Subscriber = Spring Publisher
> chore: Rename AsyncSubscriber to AsyncListener

- springwolf-examples/springwolf-kafka-example/build.gradle
- springwolf-examples/springwolf-kafka-example/src/test/java/io/github/stavshamir/springwolf/example/OpenApiGeneratorTest.java
Added an example configuration for springdoc-openapi-gradle-plugin to the springwolf-kafka-example to demonstrate how it can be used. 
To test and ensure that the plugin still works for springwolf, I also added:
* The plugin is executed before the test step
* A unit test compares the generated file with expected spec that is also used in the other test.
I'm not super happy with the testing part, because there is no way to ignore exception from springdoc-openapi-gradle-plugin. That means that if there is a problem with the application start and the plugin can not get the spec, the build will fail before the tests are executed. If that is not acceptable we can discuss more complex options ie moving this test into its own gradle task that is executed after the tests.
> Add example configuration for springdoc-openapi-gradle-plugin

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/ChannelMerger.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/ChannelMergerTest.java
Exception: Caused by: java.lang.ClassCastException: class io.github.stavshamir.springwolf.asyncapi.types.channel.operation.message.Message cannot be cast to class java.lang.Comparable (io.github.stavshamir.springwolf.asyncapi.types.channel.operation.message.Message is in unnamed module of loader 'app'; java.lang.Comparable is in module java.base of loader 'bootstrap')
> bugfix: Message is not comparable (ClassCastException)

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncAnnotationScannerUtil.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncListener.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncListenerAnnotationScanner.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncListeners.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncPublisher.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncPublisherAnnotationScanner.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncPublishers.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncAnnotationScannerUtilTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncListenerAnnotationScannerTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncPublisherAnnotationScannerTest.java
Resolving values in the annotation is helpful when spring variables are used, like `${spring.application-name}`
Also, if a listener method is able to consume multiple topics/payload types, multiple AsyncListener annotations are necessary on a single method.
> Feat: Resolve annotation headers + Multiple AsyncListener/AsyncPublisher annotation

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/SpringWolfConfigConstants.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/SpringWolfConfigProperties.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/ConsumerOperationDataScanner.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/ProducerOperationDataScanner.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncListenerAnnotationScanner.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncPublisherAnnotationScanner.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/SpringContextTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/configuration/DefaultAsyncApiDocketServiceIntegrationTest.java
- springwolf-examples/springwolf-amqp-example/src/main/resources/application.properties
- springwolf-examples/springwolf-amqp-example/src/test/java/io/github/stavshamir/springwolf/example/SpringContextTest.java
- springwolf-examples/springwolf-cloud-stream-example/src/test/java/io/github/stavshamir/springwolf/example/SpringContextTest.java
- springwolf-examples/springwolf-kafka-example/src/main/resources/application.properties
- springwolf-examples/springwolf-kafka-example/src/test/java/io/github/stavshamir/springwolf/example/SpringContextTest.java
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/stavshamir/springwolf/SpringWolfAmqpConfigConstants.java
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/stavshamir/springwolf/SpringWolfAmqpConfigProperties.java
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/MethodLevelRabbitListenerScanner.java
- springwolf-plugins/springwolf-amqp-plugin/src/test/java/io/github/stavshamir/springwolf/configuration/SpringwolfAmqpProducerConfigurationIntegrationTest.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/SpringWolfKafkaConfigConstants.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/SpringWolfKafkaConfigProperties.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/ClassLevelKafkaListenerScanner.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/MethodLevelKafkaListenerScanner.java
- springwolf-plugins/springwolf-kafka-plugin/src/test/java/io/github/stavshamir/springwolf/configuration/SpringwolfKafkaProducerConfigurationIntegrationTest.java
Allows for more fine-grain configuration, avoiding exceptions if certain listeners are broken, or if multiple scanners discover the same consumer/producer
> feat: Enable/Disable listeners per configuration

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/DefaultAsyncApiSerializerService.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/DefaultChannelsService.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/ChannelMerger.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/channel/operation/message/header/AsyncHeaders.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/schemas/DefaultSchemasService.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/DefaultAsyncApiSerializerServiceTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/serializers/KafkaOperationBindingSerializerTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/schemas/DefaultSchemasServiceTest.java
- springwolf-core/src/test/resources/asyncapi/asyncapi.json
- springwolf-core/src/test/resources/schemas/documented-definitions.json
- springwolf-examples/springwolf-amqp-example/src/test/java/io/github/stavshamir/springwolf/example/ApiIntegrationTest.java
- springwolf-examples/springwolf-amqp-example/src/test/java/io/github/stavshamir/springwolf/example/ApiIntegrationWithDockerTest.java
- springwolf-examples/springwolf-amqp-example/src/test/resources/asyncapi.json
- springwolf-examples/springwolf-cloud-stream-example/src/main/java/io/github/stavshamir/springwolf/example/configuration/AsyncApiConfiguration.java
- springwolf-examples/springwolf-cloud-stream-example/src/test/java/io/github/stavshamir/springwolf/example/ApiIntegrationTest.java
- springwolf-examples/springwolf-cloud-stream-example/src/test/java/io/github/stavshamir/springwolf/example/ApiIntegrationWithDockerTest.java
- springwolf-examples/springwolf-cloud-stream-example/src/test/resources/asyncapi.json
- springwolf-examples/springwolf-kafka-example/src/test/java/io/github/stavshamir/springwolf/example/ApiIntegrationTest.java
- springwolf-examples/springwolf-kafka-example/src/test/java/io/github/stavshamir/springwolf/example/ApiIntegrationWithDockerTest.java
- springwolf-examples/springwolf-kafka-example/src/test/java/io/github/stavshamir/springwolf/example/OpenApiGeneratorTest.java
- springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.json
Avoid usage of sorted data structures in code (like TreeMap, etc)
Library internal data structures should not have an impact on the order of the elements in the resulting asyncapi.json doc file
> chore: Sort asyncapi doc elements via objectMapper

- springwolf-add-ons/springwolf-common-model-converters/build.gradle
- springwolf-core/build.gradle
- springwolf-plugins/springwolf-amqp-plugin/build.gradle
- springwolf-plugins/springwolf-cloud-stream-plugin/build.gradle
- springwolf-plugins/springwolf-kafka-plugin/build.gradle
Regression of the spring boot update released in springwolf 0.10.3
Current artifact name: springwolf-kafka-0.10.3-plain.jar
Should be (previous behaviour): springwolf-kafka-0.10.3.jar
Relates to: https://github.com/springwolf/springwolf-core/issues/136
> Fix: Packaging jars without -plain archiveClassifier

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/SpringWolfAutoConfiguration.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/configuration/EnableAsyncApi.java
- springwolf-core/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/CustomBeanAsyncApiDocketConfiguration.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/integrationtests/SpringWolfAutoConfigurationTest.java
- springwolf-examples/springwolf-amqp-example/src/main/java/io/github/stavshamir/springwolf/example/configuration/AsyncApiConfiguration.java
- springwolf-examples/springwolf-cloud-stream-example/src/main/java/io/github/stavshamir/springwolf/example/configuration/AsyncApiConfiguration.java
- springwolf-examples/springwolf-kafka-example/src/main/java/io/github/stavshamir/springwolf/example/configuration/AsyncApiConfiguration.java
- springwolf-plugins/springwolf-amqp-plugin/README.md
- springwolf-plugins/springwolf-kafka-plugin/README.md
This is a suggestion for a spring boot auto-configuration, replacing the @EnableSpringWolf Annotation. Sie #128 
It is a 1:1 replacement of the componentscan definition in @EnableSpringWolf with a base-package that includes all plugins. (which in my eyes is not perfect, I would prefer separate package namespaces for core and plugins and separate autoconfigurations...)
Not included with this PR are the necessary updates in the documentation - I'am new to github and did not find the sources ... ;-)
> Provide Autoconfiguration, make @EnableAsyncApi deprecated and noop

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/AsyncApiSerializerService.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/DefaultAsyncApiSerializerService.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/controller/AsyncApiController.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/DefaultAsyncApiSerializerServiceTest.java
- springwolf-core/src/test/resources/asyncapi/asyncapi.yaml
Added support to create the `asyncapi` specification file in YAML.
Requesting the file to `/springwolf/docs.yaml` will provide it in YAML format. Otherwise, using the path defined by `springwolf.paths.docs` variable, concatenating `.yaml` at the end will produce the same effect
> Export to YAML

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/DefaultAsyncApiSerializerService.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/schemas/DefaultSchemasService.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/controller/dtos/MessageDtoDeserializationTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/schemas/DefaultSchemasServiceTest.java
- springwolf-core/src/test/resources/asyncapi/asyncapi.json
- springwolf-core/src/test/resources/schemas/definitions.json
- springwolf-core/src/test/resources/schemas/documented-definitions.json
- springwolf-examples/springwolf-amqp-example/src/test/resources/asyncapi.json
- springwolf-examples/springwolf-cloud-stream-example/src/test/resources/asyncapi.json
- springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.json
Fixes https://github.com/springwolf/springwolf-core/issues/169
The `exampleSetFlag` and `types` properties belong to `swagger-core` internals and are not part of the AsyncAPI specification.
See https://github.com/swagger-api/swagger-core/pull/3637#issuecomment-682370287 for some details.
This PR replaces the custom JSON ObjectMapper by the `swagger-core` one, which already contains all the needed `mixins` to properly serialize the specification.
Fixes #169 for Json Serialization
> fix: Fixed JSON serializer to not leak unintended values

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/SpringWolfConfigProperties.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/DefaultAsyncApiService.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/AsyncAPI.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/configuration/AsyncApiDocket.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/configuration/DefaultAsyncApiDocketService.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/SpringContextTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/configuration/DefaultAsyncApiDocketServiceTest.java
- springwolf-examples/springwolf-amqp-example/src/test/resources/asyncapi.json
- springwolf-examples/springwolf-cloud-stream-example/src/test/resources/asyncapi.json
- springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.json
Looking at the AsyncAPI specification I was missing support to provide the next elements:
The configuration for `defaultContentType` was not possible via SpringBoot Properties (only programatically)
Now we can indicate something like `springwolf.docket.default-content-type=application/json` (or `springwolf.docket.defaultContentType=application/json` to configure the value
It was not possible to configure the AsyncAPI identifier either (`id`)
Now we can indicate something like `springwolf.docket.id=urn:something:something` (or `springwolf.docket.id=https://something` to configure the identifier value
> Feat: Improved docket configuration

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/AbstractOperationDataScanner.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/DefaultAsyncApiServiceTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/ConsumerOperationDataScannerTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/ProducerOperationDataScannerTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncListenerAnnotationScannerTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncPublisherAnnotationScannerTest.java
- springwolf-examples/springwolf-amqp-example/src/test/resources/asyncapi.json
- springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.json
When defining an `@AsyncOperation` description like in
```
@AsyncOperation(
channelName = "channel-name",
description = "My channel description")
```
The generated AsyncAPI schema was always showing `Auto-generated description`
now properly shows the defined `description` value.
> Fix: Fixed autogenerated description

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncAnnotationScannerUtil.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/classes/AbstractAnnotatedClassScanner.java
Replaces usage of `org.apache.commons.lang3.StringUtils` with `org.springframework.util.StringUtils`.   
`org.apache.commons:commons-lang3` is not needed anymore and could be removed from dependency management (currently not declared explicityl but picked up transiently)
> replace commons.lang3.StringUtils with springframework.util.StringUtils

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/AbstractOperationDataScanner.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/DefaultAsyncApiServiceTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/ConsumerOperationDataScannerTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/ProducerOperationDataScannerTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncListenerAnnotationScannerTest.java
- springwolf-examples/springwolf-amqp-example/src/test/resources/asyncapi.json
- springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.json
While working at https://github.com/springwolf/springwolf-core/pull/189 we found out that the provided Message description was, in fact, the one associated to the Operation. As a result we decided to fully remove the description until we could fix it.
This PR adds support for Message description.
Any `Message` object, annotated with `@Schema` will use the annotation `description` value, as the Message description.
The https://www.springwolf.dev/docs/configuration/documenting-schemas documentation is already stating this scenario, so I don't think we need further documentation updates.
> feat: Added support for Message description

- build.gradle
- dependencies.gradle
- springwolf-add-ons/springwolf-common-model-converters/build.gradle
- springwolf-core/build.gradle
- springwolf-examples/springwolf-amqp-example/build.gradle
- springwolf-examples/springwolf-cloud-stream-example/build.gradle
- springwolf-examples/springwolf-kafka-example/build.gradle
- springwolf-plugins/springwolf-amqp-plugin/build.gradle
- springwolf-plugins/springwolf-cloud-stream-plugin/build.gradle
- springwolf-plugins/springwolf-kafka-plugin/build.gradle
This pull request takes care of the dependency management. There are two changes.
First, introduce a gradle plugin called 'ca.cutterslade.analyze'. This plugin is a dependency management tool which scans for used but undeclared dependencies and vice versa unused but declared dependencies. This results in clear and reliable dependencies in the project.
Second, add a explicit _dependencies.gradle_ file containing versions for dependencies which are used in subprojects. This approach is compatible with dependabot (see: [dependabot-gradle](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#gradle))
> chore: dependency management

- dependencies.gradle
- springwolf-add-ons/springwolf-common-model-converters/build.gradle
- springwolf-core/build.gradle
- springwolf-examples/springwolf-amqp-example/build.gradle
- springwolf-examples/springwolf-cloud-stream-example/build.gradle
- springwolf-examples/springwolf-kafka-example/build.gradle
- springwolf-plugins/springwolf-amqp-plugin/build.gradle
- springwolf-plugins/springwolf-cloud-stream-plugin/build.gradle
- springwolf-plugins/springwolf-kafka-plugin/build.gradle
that are not managed by spring in dependencies.gradle
Otherwise the pom file is generated without a version, which leads to errors for all projects consuming springwolf-core, ...
Addressing: https://github.com/springwolf/springwolf-core/issues/232
> chore: set and specify versions of all dependencies 

- .gitignore
- dependencies.gradle
- springwolf-add-ons/springwolf-common-model-converters/build.gradle
- springwolf-core/build.gradle
- springwolf-examples/springwolf-amqp-example/build.gradle
- springwolf-examples/springwolf-cloud-stream-example/build.gradle
- springwolf-examples/springwolf-kafka-example/build.gradle
https://github.com/swagger-api/swagger-core is a monorepo and all the group dependencies are released together.
With the merge of https://github.com/springwolf/springwolf-core/pull/240 a breaking change was introduced and the code was not compiling anymore. Also, for some reason DependaBot was not identifying the need to update the rest of the dependencies.
Now we align all the Swagger-Core related dependencies.
> build: Fixed Swagger-Core dependencies

- dependencies.gradle
- springwolf-add-ons/springwolf-common-model-converters/build.gradle
- springwolf-core/build.gradle
- springwolf-examples/springwolf-amqp-example/build.gradle
- springwolf-examples/springwolf-cloud-stream-example/build.gradle
- springwolf-examples/springwolf-kafka-example/build.gradle
- springwolf-plugins/springwolf-amqp-plugin/build.gradle
- springwolf-plugins/springwolf-kafka-plugin/build.gradle
When doing any `compileJava` task, Gradle was showing a warning
```
warning: unknown enum constant When.MAYBE
reason: class file for javax.annotation.meta.When not found
```
This issue was caused by the `javax.annotation.meta.When` enum not being available to your projects runtime (`org.springframework.lang.Nullable` references this enum, but it is not made available automatically)
Also, renamed `swaggerCoreJakartaVersion` to `swaggerCoreVersion`
The groupId is `io.swagger.core` the fact that an artifact is suffixed `-jakarta` or not doesn't change the versioning.
Also, aligned a previously missing `swagger-models` dependency.
> build: fixed compile warning

- dependencies.gradle
- springwolf-add-ons/springwolf-common-model-converters/build.gradle
- springwolf-core/build.gradle
com.fasterxml.jackson is also released together, so each artifact has the same version
> GH-242: chore: Reduce jackson dependency to single one

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/AbstractOperationDataScanner.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncAnnotationScannerUtil.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncListenerAnnotationScanner.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncMessage.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncOperation.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncPublisherAnnotationScanner.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/ConsumerData.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/OperationData.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/ProducerData.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/channel/operation/message/Message.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncAnnotationScannerUtilTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncListenerAnnotationScannerTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncPublisherAnnotationScannerTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/TestMessageBindingProcessor.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/TestOperationBindingProcessor.java
Added support for a new `@AsyncMessage` annotation. This annotation can be used as a method parameter annotation on the same method the `@AsyncPublisher` or `@AsyncListener` annotations are used.
This new `@AsyncMessage` annotation allows to enrich the AsyncAPI Operation Message with all the supported fields.
The Message payload documentation stays in the Swagger `@Schema` annotation. This new `@AsyncMessage` annotation is intended to enrich the missing values.
A special case is the description, which is available in both. Any value defined in `@AsyncMessage` has higher priority than any other default value.
> feat: Added @AsyncMessage

- build.gradle
- settings.gradle
- springwolf-examples/springwolf-amqp-example/build.gradle
- springwolf-examples/springwolf-cloud-stream-example/build.gradle
- springwolf-examples/springwolf-kafka-example/build.gradle
The current configuration also tries to publish `springwolf-add-ons`, `springwolf-examples`, `springwolf-plugins`
> chore: Only publish actual artifacts

- springwolf-core/build.gradle
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/AbstractOperationBindingProcessor.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/AsyncOperationBinding.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncAnnotationScannerUtilTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/TestAbstractOperationBindingProcessor.java
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/AmqpOperationBindingProcessor.java
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AmqpAsyncOperationBinding.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/KafkaOperationBindingProcessor.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/KafkaAsyncOperationBinding.java
So far we had 2 Operation Binding implementations: `springwolf-kafka-plugin` and `springwolf-amqp-plugin`. Now we have a new annotation that can be used to simplify the implementation of new bindings, reducing code duplicities.
Any new `OperationBindingProcessor` can extend from the new `AbstractOperationBindingProcessor`.
This PR is created as a first draft to follow up from the https://github.com/springwolf/springwolf-core/issues/288#issuecomment-1636082284 comment.
@timonback @sam0r040 What do you think of this approach? Would make sense to do something similar with the `MessageBindingProcessor`? My next step would be to create a new `GooglePubSubBinding` implementation, probably as its own plugin, using this approach.
> feat: Added an `@AsyncOperationBinding` annotation to simplify the creation of new operation bindings

- springwolf-plugins/springwolf-amqp-plugin/build.gradle
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/RabbitListenerUtil.java
- springwolf-plugins/springwolf-amqp-plugin/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/MethodLevelRabbitListenerScannerIntegrationTest.java
Add support for RabbitListener.queuesToDeclare when listing all queue names.
> Add support for RabbitListener.queuesToDeclare

- dependencies.gradle
- springwolf-examples/springwolf-cloud-stream-example/build.gradle
- springwolf-examples/springwolf-kafka-example/build.gradle
- springwolf-plugins/springwolf-cloud-stream-plugin/build.gradle
- springwolf-plugins/springwolf-kafka-plugin/build.gradle
This reverts commit 8cf45d4b
Reason:
- These dependency should be upgraded by the spring (in their versions file) or by the user
- Source: https://docs.spring.io/spring-boot/docs/current/reference/html/dependency-versions.html
- The versions appear in our pom.xml, which might not be ideal for a library to enfore this on our users
> Revert "chore(deps): Bump snakeyaml and kafka"

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/schemas/example/ExampleJsonGenerator.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/schemas/example/ExampleJsonGeneratorTest.java
This pull request is for the issue #368 
Changes in this PR:
1. Replaced StringBuilder being used in handleObjectProperties with ObjectNode to generate JSON string
2. Replaced StringBuilder being used in handleArraySchema with Arrays to generate Array string
3. Updated the tests
> Replaced the StringBuilder for generating JSON

- springwolf-plugins/springwolf-cloud-stream-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/cloudstream/CloudStreamFunctionChannelsScanner.java
- springwolf-plugins/springwolf-cloud-stream-plugin/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/cloudstream/CloudStreamFunctionChannelsScannerIntegrationTest.java
In case publish channel destination and subscribe channel destination have a same name it should merge into single channel
fixes #415
> fix: updated CloudStreamFunctionChannelsScanner scan to merge channel

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/SpringwolfAutoConfiguration.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/SpringwolfScannerConfiguration.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/SpringwolfWebConfiguration.java
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/amqp/SpringwolfAmqpProducerConfiguration.java
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/amqp/SpringwolfAmqpScannerConfiguration.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/kafka/SpringwolfKafkaProducerConfiguration.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/kafka/SpringwolfKafkaScannerConfiguration.java
- springwolf-plugins/springwolf-sns-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/sns/SpringwolfSnsProducerConfiguration.java
- springwolf-plugins/springwolf-sns-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/sns/SpringwolfSnsScannerConfiguration.java
- springwolf-plugins/springwolf-sqs-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/sqs/SpringwolfSqsProducerConfiguration.java
- springwolf-plugins/springwolf-sqs-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/sqs/SpringwolfSqsScannerConfiguration.java
Addes `@ConditionalOnMissingBean` to all Springwolf service beans. 
I made one exception:  All subclasses of `ChannelScanner` beans are not annotated. As  all `ChannelScanner` beans are collected by `DefaultChannelsService`, an application can simply define its own `ChannelScanner` bean which is recognized by DefaultChannelsService. To suppress the default Springwolf ChannelScanners, there are `*.enabled` properties for each `ChannelScanner` type. 
TBD:  is this decision ok?
> add @ConditionalOnMissingBean 

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/AbstractOperationDataScanner.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/ConsumerOperationDataScanner.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/ProducerOperationDataScanner.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/configuration/AsyncApiDocket.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/configuration/DefaultAsyncApiDocketService.java
- springwolf-core/src/main/java/io/github/stavshamir/springwolf/configuration/properties/SpringwolfConfigProperties.java
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/AmqpConsumerData.java
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/AmqpProducerData.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/KafkaConsumerData.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/KafkaProducerData.java
> chore(core): deprecated AsyncApiDocket bean

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/SpringPayloadAnnotationTypeExtractor.java
When a method defining `@AsyncGenericOperationBinding` has more than 1 argument and misses the `@Payload` annotation, the provided exception message was confusing.
Instead of `Multi-parameter KafkaListener methods must have one parameter annotated with @Payload but none was found` we now provide a more generic `Multi-parameter AsyncListener methods must have one parameter annotated with @Payload but none was found`
> fix: Improved error message

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/SpringwolfInitApplicationListener.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/integrationtests/InitModeIntegrationTest.java
This PR introduces a small change to the fail-fast initialization of AsyncApi. Until now, the initialization happend during `afterPropertiesSet()` method in `SpringWolfInitApplicationListener` - which means: after the `SpringWolfInitApplicationListener` bean and all dependents (including `AsyncApiService` etc...) have been initialized. 
The disadvantage of initializing the AsyncAPI at this point of time is, that the spring context isn't **completly** initialized, some beans may not exist in the spring-context at this moment. This may be problematic if scanner classes will for example make use of `BeanPostProcessors` or Spring AOP to detect (infrastructre) beans.
I moved the fail-fast initializing branch into the  `onApplicationEvent()` method, which means:
- the AsyncApi initialization …
> Defer fail-fast initialization to ApplicationReadyEvent

- .github/workflows/springwolf-addons.yml
- .github/workflows/springwolf-core.yml
- .github/workflows/springwolf-plugins.yml
- .github/workflows/springwolf-ui.yml
avoid that failed actions only cancel after the 6h default setting and thus resources
> add gh action timeout of 10m

- .gitignore
- build.gradle
- springwolf-examples/springwolf-amqp-example/src/test/java/io/github/stavshamir/springwolf/example/amqp/ApiSystemTest.java
- springwolf-examples/springwolf-amqp-example/src/test/java/io/github/stavshamir/springwolf/example/amqp/BaseApiIntegrationTest.java
- springwolf-examples/springwolf-amqp-example/src/test/java/io/github/stavshamir/springwolf/example/amqp/ProducerSystemTest.java
- springwolf-examples/springwolf-cloud-stream-example/src/test/java/io/github/stavshamir/springwolf/example/cloudstream/ApiIntegrationTest.java
- springwolf-examples/springwolf-cloud-stream-example/src/test/java/io/github/stavshamir/springwolf/example/cloudstream/ApiSystemTest.java
- springwolf-examples/springwolf-kafka-example/src/test/java/io/github/stavshamir/springwolf/example/kafka/ApiIntegrationTest.java
- springwolf-examples/springwolf-kafka-example/src/test/java/io/github/stavshamir/springwolf/example/kafka/ApiIntegrationWithActuatorIntegrationTest.java
- springwolf-examples/springwolf-kafka-example/src/test/java/io/github/stavshamir/springwolf/example/kafka/ApiSystemTest.java
- springwolf-examples/springwolf-kafka-example/src/test/java/io/github/stavshamir/springwolf/example/kafka/OpenApiGeneratorSystemTest.java
- springwolf-examples/springwolf-kafka-example/src/test/java/io/github/stavshamir/springwolf/example/kafka/ProducerSystemTest.java
- springwolf-examples/springwolf-sns-example/src/test/java/io/github/stavshamir/springwolf/example/sns/ApiIntegrationTest.java
- springwolf-examples/springwolf-sns-example/src/test/java/io/github/stavshamir/springwolf/example/sns/ApiSystemTest.java
- springwolf-examples/springwolf-sqs-example/src/test/java/io/github/stavshamir/springwolf/example/sqs/ApiIntegrationTest.java
- springwolf-examples/springwolf-sqs-example/src/test/java/io/github/stavshamir/springwolf/example/sqs/ApiSystemTest.java
- springwolf-examples/springwolf-sqs-example/src/test/java/io/github/stavshamir/springwolf/example/sqs/ProducerSystemTest.java
While IntegrationTest allows to use the SpringContext, SystemTest goes one level higher in the test pyramid and runs using the docker containers.
Motivation: SystemTest take longer to run as the docker containers need to be started. IntegrationTest strike a balance between fast to execute and high test coverage.
> test: introduce systemTest target

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/AnnotationUtil.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/AnnotationUtilTest.java
One example is the `@KafkaListener` annotation reported in GH-510
Closes https://github.com/springwolf/springwolf-core/issues/510
> fix(core): handle meta annotations using spring `@AliasFor`

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> chore: disable owasp nodejs checking

- springwolf-core/src/main/java/io/github/stavshamir/springwolf/schemas/SwaggerSchemaUtil.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/SpringContextIntegrationTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/DefaultAsyncApiServiceIntegrationTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/fixtures/MinimalIntegrationTestContextConfiguration.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/integrationtests/AsyncApiDocumentIntegrationTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/integrationtests/AutoConfigurationIntegrationTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/integrationtests/InitModeIntegrationTest.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/integrationtests/application/basic/TestApplication.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/integrationtests/application/listener/ListenerApplication.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/integrationtests/application/polymorphic/PolymorphicPayloadApplication.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/integrationtests/application/publisher/PublisherApplication.java
- springwolf-core/src/test/java/io/github/stavshamir/springwolf/schemas/SwaggerSchemaUtilTest.java
Add support for discriminator field as requested in https://github.com/springwolf/springwolf-core/issues/160
To test, the integration tests in core have been extended to allow multiple Spring Boot test applications (via different packages).
This allows to test springwolf-core using multiple, smaller sized integration tests.
An integration test is used for the discriminator field, since multiple components have to work together to generate the correct AsyncApi document output.
> Add discriminator field support + better integration tests in core

- springwolf-ui/src/app/components/channels/channel-main/channel-main.component.html
Hello! Thanks for great project!
submitted issue with explaination https://github.com/springwolf/springwolf-core/issues/650
Problem - no schema for headers without schema in Kafka Listeners (HeadersNotDocumented schema).
Scenario - user wants to send custom headers in springwolf kafka ui, headers are not defined in schema and changes in internal implementation.
Now there are two workarounds to this:
1) Define headers for schema using annotations
2) Add example to schema HeadersNotDocumented
> fix(ui): Make edit header view available by default in ui

- springwolf-bindings/springwolf-sns-binding/src/main/java/io/github/springwolf/bindings/sns/configuration/SpringwolfSnsBindingAutoConfiguration.java
The new SNS Binding Beans were wrongly named as `sqsMessageBindingProcessor` and `sqsOperationBindingProcessor`
This was causing a "A bean with that name has already been defined in class path resource" when using together the  `springwolf-sns-binding` and the `springwolf-sqs-binding` libraries
> (fix) Fixed bug with new SNS Binding

- springwolf-add-ons/springwolf-kotlinx-serialization-model-converter/src/main/kotlin/io/github/springwolf/addons/kotlinx_serialization_model_converter/converter/KotlinxSerializationModelConverter.kt
- springwolf-add-ons/springwolf-kotlinx-serialization-model-converter/src/test/java/io/github/springwolf/addons/kotlinx_serialization_model_converter/converter/KotlinxSerializationTypeConverterTest.java
- springwolf-add-ons/springwolf-kotlinx-serialization-model-converter/src/test/kotlin/io.github.springwolf.addons.kotlinx_serialization_model_converter.converter/SampleEvent.kt
The new Kotlin Serialization converter was not properly managing the `Collection` types.
> (fix) Kotlin serializer for Collection

- springwolf-asyncapi/src/main/java/io/github/springwolf/asyncapi/v3/bindings/kafka/KafkaChannelBinding.java
- springwolf-asyncapi/src/main/java/io/github/springwolf/asyncapi/v3/bindings/kafka/KafkaChannelTopicConfiguration.java
- springwolf-asyncapi/src/main/java/io/github/springwolf/asyncapi/v3/bindings/kafka/KafkaMessageBinding.java
- springwolf-asyncapi/src/main/java/io/github/springwolf/asyncapi/v3/bindings/kafka/KafkaOperationBinding.java
- springwolf-asyncapi/src/main/java/io/github/springwolf/asyncapi/v3/bindings/kafka/KafkaServerBinding.java
- springwolf-asyncapi/src/test/java/io/github/springwolf/asyncapi/v3/bindings/kafka/KafkaBindingTest.java
- springwolf-asyncapi/src/test/resources/v3/asyncapi/asyncapi.json
- springwolf-asyncapi/src/test/resources/v3/asyncapi/asyncapi.yaml
- springwolf-asyncapi/src/test/resources/v3/bindings/kafka/kafka-channel.yaml
- springwolf-asyncapi/src/test/resources/v3/bindings/kafka/kafka-message.yaml
- springwolf-asyncapi/src/test/resources/v3/bindings/kafka/kafka-operation.yaml
- springwolf-asyncapi/src/test/resources/v3/bindings/kafka/kafka-server.yaml
- springwolf-asyncapi/src/test/resources/v3/bindings/kafka/kafka-topic.yaml
- springwolf-examples/springwolf-kafka-example/src/test/java/io/github/springwolf/examples/kafka/ApiIntegrationTest.java
- springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.json
- springwolf-ui/package-lock.json
- springwolf-ui/package.json
As per https://github.com/asyncapi/bindings/tree/master/kafka
> (chore) Updated AsyncAPI Kafka binding to version 0.5.0

- springwolf-add-ons/springwolf-kotlinx-serialization-model-converter/src/main/kotlin/io/github/springwolf/addons/kotlinx_serialization_model_converter/converter/KotlinxSerializationModelConverter.kt
- springwolf-add-ons/springwolf-kotlinx-serialization-model-converter/src/test/java/io/github/springwolf/addons/kotlinx_serialization_model_converter/converter/KotlinxSerializationTypeConverterTest.java
- springwolf-add-ons/springwolf-kotlinx-serialization-model-converter/src/test/resources/fqn.json
- springwolf-add-ons/springwolf-kotlinx-serialization-model-converter/src/test/resources/simple.json
Fixed 2 bugs with the Kotlinx Module
* When using FQN, the parent classes where using the simple name instead of the fqn
* Nested classes where wrongly defined more than one time
> fix: Fixes to the Kotlinx Module

- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/operations/OperationMerger.java
- springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/operations/OperationMergerTest.java
- springwolf-examples/springwolf-amqp-example/src/test/resources/asyncapi.json
Message references are now alphabetically sorted.
When an Operation has multiple messages, the resulting order depends on how the classes are parsed. This can produce slightly different results in different machines, making problematic the comparison for changes.
> fix: Sort Messages references

- springwolf-bindings/springwolf-googlepubsub-binding/src/main/java/io/github/springwolf/bindings/googlepubsub/scanners/channels/GooglePubSubChannelBindingProcessor.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/bindings/channels/ChannelBindingProcessor.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/common/utils/AsyncAnnotationUtil.java
- springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/bindings/processor/TestChannelBindingProcessor.java
- springwolf-examples/springwolf-cloud-stream-example/src/main/java/io/github/springwolf/examples/cloudstream/configuration/ConsumerClass.java
- springwolf-examples/springwolf-cloud-stream-example/src/main/resources/application.properties
- springwolf-examples/springwolf-cloud-stream-example/src/test/resources/asyncapi.json
- springwolf-plugins/springwolf-cloud-stream-plugin/src/main/java/io/github/springwolf/plugins/cloudstream/asyncapi/scanners/channels/CloudStreamFunctionChannelsScanner.java
- springwolf-plugins/springwolf-cloud-stream-plugin/src/main/java/io/github/springwolf/plugins/cloudstream/asyncapi/scanners/common/FunctionalChannelBeanBuilder.java
- springwolf-plugins/springwolf-cloud-stream-plugin/src/main/java/io/github/springwolf/plugins/cloudstream/asyncapi/scanners/common/FunctionalChannelBeanData.java
- springwolf-plugins/springwolf-cloud-stream-plugin/src/main/java/io/github/springwolf/plugins/cloudstream/asyncapi/scanners/operations/CloudStreamFunctionOperationsScanner.java
- springwolf-plugins/springwolf-cloud-stream-plugin/src/main/java/io/github/springwolf/plugins/cloudstream/configuration/SpringwolfCloudStreamAutoConfiguration.java
- springwolf-plugins/springwolf-cloud-stream-plugin/src/test/java/io/github/springwolf/plugins/cloudstream/asyncapi/scanners/common/FunctionalChannelBeanBuilderTest.java
Until now, cloud stream plugin could auto detect Consumer/Supplier/Function bean methods:
```java
@Configuration
public class MyConsumerConfiguration {
@Bean
public Consumer<String> myConsumer() {
return log::info;
}
}
```
But the following valid configuration was not detected:
```java
@Component
public class MyConsumer implements Consumer<String> {
@Override
public void accept(String payload) {
log.info(payload);
}
}
```
This PR adds support for auto-detections of Component class in cloud stream plugin. These now lead to the creation of channels and operations automatically.
Additionally, to support this feature `ChannelBindingProcessor` now accepts `AnnotatedElement` instead of `Method`. Bindings could now potentially be used on classes as well, but I did not change the only existing …
> Add support for Component classes for spring cloud stream plugin (#684)

- springwolf-add-ons/springwolf-generic-binding/build.gradle
- springwolf-add-ons/springwolf-generic-binding/src/main/java/io/github/springwolf/addons/generic_binding/annotation/processor/PropertiesUtil.java
- springwolf-add-ons/springwolf-generic-binding/src/test/java/io/github/springwolf/addons/generic_binding/annotation/processor/AsyncGenericOperationBindingProcessorTest.java
When using the Generic Binding, it was not possible to define an array value. Here we add support for it.
Example: "key=[value1, value2, value3]"
> feat: Added support for arrays to the Generic Binding

- springwolf-bindings/springwolf-googlepubsub-binding/src/main/java/io/github/springwolf/bindings/googlepubsub/annotations/GooglePubSubAsyncChannelBinding.java
- springwolf-bindings/springwolf-googlepubsub-binding/src/main/java/io/github/springwolf/bindings/googlepubsub/annotations/GooglePubSubAsyncMessageBinding.java
- springwolf-bindings/springwolf-googlepubsub-binding/src/main/java/io/github/springwolf/bindings/googlepubsub/scanners/channels/GooglePubSubChannelBindingProcessor.java
- springwolf-bindings/springwolf-googlepubsub-binding/src/main/java/io/github/springwolf/bindings/googlepubsub/scanners/messages/GooglePubSubMessageBindingProcessor.java
- springwolf-bindings/springwolf-sns-binding/src/main/java/io/github/springwolf/bindings/sns/annotations/SnsAsyncOperationBinding.java
- springwolf-bindings/springwolf-sns-binding/src/main/java/io/github/springwolf/bindings/sns/scanners/messages/SnsMessageBindingProcessor.java
- springwolf-bindings/springwolf-sns-binding/src/main/java/io/github/springwolf/bindings/sns/scanners/operations/SnsOperationBindingProcessor.java
- springwolf-bindings/springwolf-sqs-binding/src/main/java/io/github/springwolf/bindings/sqs/annotations/SqsAsyncOperationBinding.java
- springwolf-bindings/springwolf-sqs-binding/src/main/java/io/github/springwolf/bindings/sqs/scanners/messages/SqsMessageBindingProcessor.java
- springwolf-bindings/springwolf-sqs-binding/src/main/java/io/github/springwolf/bindings/sqs/scanners/operations/SqsOperationBindingProcessor.java
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/springwolf/plugins/amqp/asyncapi/annotations/AmqpAsyncOperationBinding.java
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/springwolf/plugins/amqp/asyncapi/scanners/bindings/messages/AmqpMessageBindingProcessor.java
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/springwolf/plugins/amqp/asyncapi/scanners/bindings/operations/AmqpOperationBindingProcessor.java
- springwolf-plugins/springwolf-jms-plugin/src/main/java/io/github/springwolf/plugins/jms/asyncapi/annotations/JmsAsyncOperationBinding.java
- springwolf-plugins/springwolf-jms-plugin/src/main/java/io/github/springwolf/plugins/jms/asyncapi/scanners/bindings/messages/JmsMessageBindingProcessor.java
- springwolf-plugins/springwolf-jms-plugin/src/main/java/io/github/springwolf/plugins/jms/asyncapi/scanners/bindings/operations/JmsOperationBindingProcessor.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/springwolf/plugins/kafka/asyncapi/annotations/KafkaAsyncOperationBinding.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/springwolf/plugins/kafka/asyncapi/scanners/bindings/messages/KafkaMessageBindingProcessor.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/springwolf/plugins/kafka/asyncapi/scanners/bindings/operations/KafkaOperationBindingProcessor.java
- springwolf-plugins/springwolf-sns-plugin/src/main/java/io/github/springwolf/plugins/sns/annotations/SnsAsyncOperationBinding.java
- springwolf-plugins/springwolf-sns-plugin/src/main/java/io/github/springwolf/plugins/sns/asyncapi/scanners/bindings/messages/SnsMessageBindingProcessor.java
- springwolf-plugins/springwolf-sns-plugin/src/main/java/io/github/springwolf/plugins/sns/asyncapi/scanners/bindings/operations/SnsOperationBindingProcessor.java
- springwolf-plugins/springwolf-sqs-plugin/src/main/java/io/github/springwolf/plugins/sqs/annotations/SqsAsyncOperationBinding.java
- springwolf-plugins/springwolf-sqs-plugin/src/main/java/io/github/springwolf/plugins/sqs/asyncapi/scanners/bindings/messages/SqsMessageBindingProcessor.java
- springwolf-plugins/springwolf-sqs-plugin/src/main/java/io/github/springwolf/plugins/sqs/asyncapi/scanners/bindings/operations/SqsOperationBindingProcessor.java
the field is fixed by the spec and should not be modified by the user
> chore(bindings)!: remove type field from protocol specific binding annotations

- springwolf-add-ons/springwolf-kotlinx-serialization-model-converter/src/main/kotlin/io/github/springwolf/addons/kotlinx_serialization_model_converter/converter/KotlinxSerializationModelConverter.kt
- springwolf-add-ons/springwolf-kotlinx-serialization-model-converter/src/test/java/io/github/springwolf/addons/kotlinx_serialization_model_converter/converter/KotlinxSerializationTypeConverterTest.java
- springwolf-add-ons/springwolf-kotlinx-serialization-model-converter/src/test/kotlin/io.github.springwolf.addons.kotlinx_serialization_model_converter.converter/SampleEvent.kt
Fixes #707. Adds basic polymorphism support to Kotlinx serialization
> (feat) Polymorphism support for kotlinx serialization

- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/common/AsyncAnnotationScanner.java
- springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/operations/annotations/AsyncAnnotationOperationsScannerTest.java
When a class is inheriting annotated methods from a superclass, the code is now properly parsing those methods for annotations.
This development allows to parse annotations from abstract classes or other inheritance classes, where the annotations are defined in a common class.
> (feat) Add support to parse Annotations from super classes

- springwolf-add-ons/springwolf-kotlinx-serialization-model-converter/build.gradle
- springwolf-add-ons/springwolf-kotlinx-serialization-model-converter/src/main/java/io/github/springwolf/addons/kotlinx_serialization_model_converter/configuration/KotlinxSerializationModelConverterAutoConfiguration.java
- springwolf-core/src/main/java/io/github/springwolf/core/configuration/properties/SpringwolfConfigConstants.java
When the Kotlinx Serialization Module was available in an environment without the `springwolf.use-fqn` the code was failing, since it was trying to inject the variable.
The code is now loading the converter **only** if `springwolf.enabled` is `true` (default value). The `springwolf.use-fqn` is also defaulting to `true`.
This solution fixes the identified issue.
> (fix) Fixed a bug loading the Kotlinx Module without `use-fqn` variable

- springwolf-ui/src/app/components/channels/channel-main/channel-main.component.spec.ts
- springwolf-ui/src/app/components/channels/channel-main/channel-main.component.ts
- springwolf-ui/src/app/components/channels/channels.component.html
- springwolf-ui/src/app/components/channels/channels.component.spec.ts
- springwolf-ui/src/app/components/channels/channels.component.ts
- springwolf-ui/src/app/components/mock-components.spec.ts
- springwolf-ui/src/app/components/servers/servers.component.spec.ts
- springwolf-ui/src/app/service/mock/mock-asyncapi.service.ts
- refactored 3 test as a start
- testing with actual (amqp) mock data (can be extended later)
> test: use angular testing library for component tests

- .github/workflows/gh-issue-comment.yml
- .github/workflows/gh-issues.yml
Feel free to suggested better messages. The intention is to keep the user in the loop regarding the current status of the issue.
Current practice:
An issue is kept open until the release is available. To indicate that an issue has been addressed/solved, we continue to add the `staged for release` label manually.
(Similarly, the `waiting for feedback` label is automatically removed when a user ( = non Springwolf member) comments)
Tested in https://github.com/timonback/springwolf-core/issues/124
> chore: comment on issues w.r.t staged_for_release, waiting_for_feedback label

- springwolf-examples/e2e/playwright.config.ts
Assumes that the tester has build new docker images
Intention: reduce the risk that code changes have been made (core, ui), but the application tested in the ui tests is not refreshed
> chore(e2e): restart examples docker containers

- springwolf-ui/src/app/service/asyncapi/asyncapi-mapper.service.ts
- springwolf-ui/src/app/service/asyncapi/models/schema.model.ts
Visualizes the any,all,oneOf schema in the ui.
This is a very basic implementation, which simply extracts the schema.
Better implementations may show the actual any,all,oneOf schema relationships
CC: @aerfus 
Relates to GH-730
> feat(ui): handle allOf schemas

- springwolf-asyncapi/src/main/java/io/github/springwolf/asyncapi/v3/model/channel/message/MessageReference.java
- springwolf-asyncapi/src/test/java/io/github/springwolf/asyncapi/v3/jackson/DefaultAsyncApiSerializerServiceIntegrationTest.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/components/DefaultComponentsService.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/channels/AsyncAnnotationChannelsScanner.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/channels/annotations/SpringAnnotationMethodLevelChannelsScanner.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/common/MessageHelper.java
- springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/channels/ChannelMergerTest.java
- springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/channels/annotations/AsyncAnnotationChannelsScannerTest.java
- springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/operations/OperationMergerTest.java
- springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/operations/annotations/AsyncAnnotationOperationsScannerTest.java
- springwolf-plugins/springwolf-cloud-stream-plugin/src/main/java/io/github/springwolf/plugins/cloudstream/asyncapi/scanners/channels/CloudStreamFunctionChannelsScanner.java
- springwolf-plugins/springwolf-cloud-stream-plugin/src/test/java/io/github/springwolf/plugins/cloudstream/asyncapi/scanners/channels/CloudStreamFunctionChannelsScannerIntegrationTest.java
> chore(core): use messageId internally

- springwolf-core/src/main/java/io/github/springwolf/core/controller/PublishingBaseController.java
- springwolf-plugins/springwolf-jms-plugin/src/test/java/io/github/springwolf/plugins/jms/controller/SpringwolfJmsControllerIntegrationTest.java
- springwolf-plugins/springwolf-kafka-plugin/src/test/java/io/github/springwolf/plugins/kafka/controller/SpringwolfKafkaControllerIntegrationTest.java
- springwolf-ui/src/app/components/channels/channel-main/channel-main.component.html
- springwolf-ui/src/app/components/channels/channel-main/channel-main.component.ts
- springwolf-ui/src/app/service/mock/mock-server.ts
- springwolf-ui/src/app/service/publisher.service.ts
This uses a trivial approach of adding a GET endpoint per protocol (no single combined one) to indicate to the ui, whether publishing is enabled.
Relates to https://github.com/springwolf/springwolf-core/issues/609
> feat(core): show publish button in ui only when publishing is enabled

- .github/workflows/publish-releases.yml
- .github/workflows/springwolf-addons.yml
- .github/workflows/springwolf-asyncapi.yml
- .github/workflows/springwolf-bindings.yml
- .github/workflows/springwolf-core.yml
- .github/workflows/springwolf-plugins.yml
- .github/workflows/springwolf-ui.yml
- RELEASING.md
- build.gradle
Uses: https://github.com/gradle-nexus/publish-plugin
Based on the documentation, the existing secrets can be used.
Also, we use the gradle version field to indiciate whether it is a release or SNAPSHOT version.
The plugin uses this to decide which repo url to use
> Enable automatic nexus publishing

- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/annotations/AsyncOperation.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/common/utils/AsyncAnnotationUtil.java
- springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/common/utils/AsyncAnnotationUtilTest.java
> feat(core): Make `@AsyncOperation.Headers.Header#value` optional

- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/common/AsyncAnnotationScanner.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/common/ClassLevelAnnotationScanner.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/common/MethodLevelAnnotationScanner.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/common/payload/NamedSchemaObject.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/common/payload/PayloadService.java
- springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/springwolf/plugins/kafka/asyncapi/scanners/common/header/AsyncHeadersForKafkaBuilder.java
relates to https://github.com/springwolf/springwolf-core/issues/792
> fix(core): handle nullable schema in NamedSchemaObject

- springwolf-core/src/main/java/io/github/springwolf/core/configuration/SpringwolfUiResourceConfiguration.java
Only use SpringwolfUiResourceConfiguration if the required beans are present in the spring context (WebMvcProperties, WebProperties)
Fixes https://github.com/springwolf/springwolf-core/issues/866
> fix(core): Fix startup when Spring WebMVC is not used

- springwolf-ui/src/app/components/new/schema/schema.component.css
- springwolf-ui/src/app/components/new/schema/schema.component.html
- springwolf-ui/src/app/components/new/schemas/schemas.component.html
- springwolf-ui/src/app/components/schemas/range/schema-range.component.spec.ts
- springwolf-ui/src/app/models/channel.model.ts
- springwolf-ui/src/app/models/schema.model.ts
- springwolf-ui/src/app/service/asyncapi/asyncapi-mapper.service.ts
- springwolf-ui/src/app/service/mock/init-values.ts
Adds the link back to the channel operation or schema - when navigating by clicks
> feat(ui): show used by in schema

- springwolf-core/build.gradle
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/components/examples/walkers/yaml/DefaultExampleYamlValueSerializer.java
- springwolf-core/src/main/java/io/github/springwolf/core/configuration/SpringwolfAutoConfiguration.java
- springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/components/DefaultYamlComponentsServiceIntegrationTest.java
- springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/components/examples/walkers/DefaultSchemaWalkerYamlIntegrationTest.java
- springwolf-core/src/test/resources/schemas/yaml/annotation-definitions-yaml.json
- springwolf-core/src/test/resources/schemas/yaml/array-definitions-yaml.json
- springwolf-core/src/test/resources/schemas/yaml/complex-definitions-yaml.json
- springwolf-core/src/test/resources/schemas/yaml/definitions-yaml.json
- springwolf-core/src/test/resources/schemas/yaml/documented-definitions-yaml.json
- springwolf-core/src/test/resources/schemas/yaml/generics-wrapper-definitions-yaml.json
- springwolf-core/src/test/resources/schemas/yaml/json-type-definitions-yaml.json
- springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.json
- springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.yaml
Since js `@asyncapi/parser@3.2.1`, the workaround for async api studio for date strings to need quotes is no longer needed
> feat(core): remove studio work-around for yaml

- .github/workflows/springwolf-core.yml
- .github/workflows/springwolf-plugins.yml
- .github/workflows/springwolf-ui.yml
- springwolf-ui/jest.config.js
- springwolf-ui/package-lock.json
- springwolf-ui/package.json
Assumption: the checks will go only go green after the merge due to how gh manages permissions in pipelines
> chore(gh): publish test reports

- springwolf-examples/springwolf-amqp-example/src/test/java/io/github/springwolf/examples/amqp/ApiSystemTest.java
- springwolf-examples/springwolf-amqp-example/src/test/java/io/github/springwolf/examples/amqp/ProducerSystemTest.java
- springwolf-examples/springwolf-cloud-stream-example/src/test/java/io/github/springwolf/examples/cloudstream/ApiSystemTest.java
- springwolf-examples/springwolf-jms-example/src/test/java/io/github/springwolf/examples/jms/ApiSystemTest.java
- springwolf-examples/springwolf-jms-example/src/test/java/io/github/springwolf/examples/jms/ProducerSystemTest.java
- springwolf-examples/springwolf-kafka-example/src/test/java/io/github/springwolf/examples/kafka/ApiSystemTest.java
- springwolf-examples/springwolf-kafka-example/src/test/java/io/github/springwolf/examples/kafka/ProducerSystemTest.java
- springwolf-examples/springwolf-sns-example/src/test/java/io/github/springwolf/examples/sns/ApiSystemTest.java
- springwolf-examples/springwolf-sqs-example/src/test/java/io/github/springwolf/examples/sqs/ApiSystemTest.java
- springwolf-examples/springwolf-sqs-example/src/test/java/io/github/springwolf/examples/sqs/ProducerSystemTest.java
- springwolf-examples/springwolf-stomp-example/src/test/java/io/github/springwolf/examples/stomp/ApiSystemTest.java
By default, a DockerComposeContainer copies the full gradle project directory into container. When running tests, the `build/test-results/test/binary/output.bin` file is written, which can get large. This file is not required for the tests and the test container default is overwritten to a single file (i.e. `.env`)
Original error messages:
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image docker/compose com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"unexpected EOF"} java.io.IOException: Request to write '8192' bytes exceeds size in header of '2064381' bytes for entry
> test: improve testcontainer test stability

- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/bindings/BindingFactory.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/common/MessageHelper.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/common/message/SpringAnnotationMessagesService.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/common/operation/SpringAnnotationOperationService.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/operations/annotations/SpringAnnotationClassLevelOperationsScanner.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/operations/annotations/SpringAnnotationMethodLevelOperationsScanner.java
- springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/common/operation/SpringAnnotationOperationServiceTest.java
- springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/operations/annotations/SpringAnnotationClassLevelOperationsScannerTest.java
- springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/operations/annotations/SpringAnnotationMethodLevelOperationsScannerTest.java
- springwolf-examples/e2e/tests/publishing.spec.ts
- springwolf-examples/springwolf-amqp-example/src/main/java/io/github/springwolf/examples/amqp/configuration/RabbitConfiguration.java
- springwolf-examples/springwolf-amqp-example/src/main/java/io/github/springwolf/examples/amqp/consumers/ExampleConsumer.java
- springwolf-examples/springwolf-amqp-example/src/test/java/io/github/springwolf/examples/amqp/SpringContextIntegrationTest.java
- springwolf-examples/springwolf-amqp-example/src/test/resources/asyncapi.json
- springwolf-examples/springwolf-amqp-example/src/test/resources/asyncapi.yaml
- springwolf-plugins/springwolf-amqp-plugin/build.gradle
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/springwolf/plugins/amqp/asyncapi/scanners/bindings/AmqpBindingFactory.java
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/springwolf/plugins/amqp/asyncapi/scanners/bindings/RabbitListenerUtil.java
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/springwolf/plugins/amqp/asyncapi/scanners/bindings/RabbitListenerUtilContext.java
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/springwolf/plugins/amqp/asyncapi/scanners/channels/RabbitQueueBeanScanner.java
- springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/springwolf/plugins/amqp/configuration/SpringwolfAmqpScannerConfiguration.java
- springwolf-plugins/springwolf-amqp-plugin/src/test/java/io/github/springwolf/plugins/amqp/asyncapi/scanners/bindings/RabbitListenerUtilContextTest.java
- springwolf-plugins/springwolf-amqp-plugin/src/test/java/io/github/springwolf/plugins/amqp/asyncapi/scanners/bindings/RabbitListenerUtilTest.java
- springwolf-plugins/springwolf-amqp-plugin/src/test/java/io/github/springwolf/plugins/amqp/asyncapi/scanners/channels/RabbitQueueBeanScannerTest.java
- springwolf-plugins/springwolf-stomp-plugin/src/main/java/io/github/springwolf/plugins/stomp/asyncapi/scanners/operation/annotations/SendToCustomizer.java
- springwolf-plugins/springwolf-stomp-plugin/src/main/java/io/github/springwolf/plugins/stomp/asyncapi/scanners/operation/annotations/SendToUserCustomizer.java
- springwolf-plugins/springwolf-stomp-plugin/src/test/java/io/github/springwolf/plugins/stomp/asyncapi/scanners/operation/annotations/SendToCustomizerTest.java
- springwolf-plugins/springwolf-stomp-plugin/src/test/java/io/github/springwolf/plugins/stomp/asyncapi/scanners/operation/annotations/SendToUserCustomizerTest.java
Extracted from https://github.com/springwolf/springwolf-core/pull/886
This is missing the link between exchanges to the target queues, as requested in the amqp binding spec
> feat(amqp): differentiate between exchange and queue

- springwolf-ui/build.gradle
Now, Intellij will include the ui when the application is started via the Application class (as alternative to gradle bootRun task)
> chore(ui): register build task into gradle assemble lifecycle

- springwolf-core/src/main/java/io/github/springwolf/core/configuration/SpringwolfWebConfiguration.java
- springwolf-core/src/main/java/io/github/springwolf/core/configuration/properties/SpringwolfConfigProperties.java
- springwolf-core/src/main/java/io/github/springwolf/core/controller/UiConfigController.java
- springwolf-core/src/test/java/io/github/springwolf/core/configuration/properties/SpringwolfConfigPropertiesIntegrationTest.java
- springwolf-examples/springwolf-amqp-example/src/main/resources/application.properties
- springwolf-examples/springwolf-cloud-stream-example/src/main/resources/application.properties
- springwolf-examples/springwolf-jms-example/src/main/resources/application.properties
- springwolf-examples/springwolf-kafka-example/src/main/resources/application.properties
- springwolf-examples/springwolf-kafka-example/src/test/resources/ui-config.json
- springwolf-examples/springwolf-sns-example/src/main/resources/application.properties
- springwolf-examples/springwolf-sqs-example/src/main/resources/application.properties
- springwolf-examples/springwolf-stomp-example/src/main/resources/application.properties
- springwolf-ui/src/app/components/header/header.component.html
- springwolf-ui/src/app/components/header/header.component.spec.ts
- springwolf-ui/src/app/service/asyncapi/models/ui.model.ts
- springwolf-ui/src/app/service/ui.service.ts
This PR introduces the new feature required in #1001
> Configure UI default settings

- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/operations/DefaultOperationsService.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/operations/OperationMerger.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/operations/OperationsInClassScanner.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/operations/OperationsInClassScannerAdapter.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/operations/annotations/AsyncAnnotationClassLevelOperationsScanner.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/operations/annotations/AsyncAnnotationMethodLevelOperationsScanner.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/operations/annotations/SpringAnnotationClassLevelOperationsScanner.java
- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/operations/annotations/SpringAnnotationMethodLevelOperationsScanner.java
- springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/operations/DefaultOperationsServiceIntegrationTest.java
- springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/operations/OperationMergerTest.java
- springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/operations/OperationsInClassScannerAdapterTest.java
- springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/operations/annotations/AsyncAnnotationClassLevelOperationsScannerTest.java
- springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/operations/annotations/AsyncAnnotationMethodLevelOperationsScannerTest.java
- springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/operations/annotations/SpringAnnotationClassLevelOperationsScannerTest.java
- springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/operations/annotations/SpringAnnotationMethodLevelOperationsScannerTest.java
- springwolf-plugins/springwolf-cloud-stream-plugin/src/main/java/io/github/springwolf/plugins/cloudstream/asyncapi/scanners/operations/CloudStreamFunctionOperationsScanner.java
Possible because Operation@operationId added.
Continuation of 0eaa374f0a9e5cd9f33daeaec7a52bb4150a6a4e
> refactor(core): simplify OperationsInClassScanner interface

- springwolf-ui/src/app/service/asyncapi/asyncapi-mapper.service.ts
- springwolf-ui/src/app/service/asyncapi/models/schema.model.ts
Relates to https://github.com/springwolf/springwolf-core/issues/1133
> bugfix(ui): fix lookup for oneof nested schemas

- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/classes/spring/annotations/AnnotationClassScanner.java
- springwolf-core/src/main/java/io/github/springwolf/core/configuration/docket/AsyncApiDocket.java
- springwolf-core/src/main/java/io/github/springwolf/core/configuration/properties/SpringwolfConfigProperties.java
- springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/classes/spring/ComponentClassScannerIntegrationTest.java
For our services, we want a central SpringWolf configuration coming from a shared lib. 
This is not possible with a single base package as the services have different base packages with no common root.
This PR tries to improve that.
Thanks!
> allow multiple base packages, comma-separated

- springwolf-plugins/springwolf-cloud-stream-plugin/src/main/java/io/github/springwolf/plugins/cloudstream/asyncapi/scanners/common/FunctionalChannelBeanBuilder.java
- springwolf-plugins/springwolf-cloud-stream-plugin/src/test/java/io/github/springwolf/plugins/cloudstream/asyncapi/scanners/common/FunctionalChannelBeanBuilderTest.java
Since a bean with a functional interface could be a child interface or child class, the whole class-hierarchy should be considered.
Fixes #1260
> Fix functional beans that use inheritance

- springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/components/examples/walkers/DefaultSchemaWalker.java
It has been unclear that the text after a colon is a schema's name.  
This PR makes this clear.
> (refactor): improve exception message

- springwolf-examples/springwolf-sqs-example/src/test/java/io/github/springwolf/examples/sqs/SqsProducerSystemTest.java
- springwolf-plugins/springwolf-sns-plugin/src/main/java/io/github/springwolf/plugins/sns/controller/SpringwolfSnsController.java
- springwolf-plugins/springwolf-sns-plugin/src/main/java/io/github/springwolf/plugins/sns/producer/SpringwolfSnsProducer.java
- springwolf-plugins/springwolf-sns-plugin/src/test/java/io/github/springwolf/plugins/sns/producer/SpringwolfSnsProducerTest.java
- springwolf-plugins/springwolf-sqs-plugin/src/main/java/io/github/springwolf/plugins/sqs/controller/SpringwolfSqsController.java
- springwolf-plugins/springwolf-sqs-plugin/src/main/java/io/github/springwolf/plugins/sqs/producer/SpringwolfSqsProducer.java
- springwolf-plugins/springwolf-sqs-plugin/src/test/java/io/github/springwolf/plugins/sqs/producer/SpringwolfSqsProducerTest.java
**Why ?**
Because when we send message from springwolf UI, headers are not send
**What does PR contain ?**
The headers defined in Springwolf's SNS UI are sent with the message (like previous PR for SQS).
Uniformity of header management between the SQS/SNS/JMS/... plugins.
> feat(sns): add SNS headers when sending message from springwolf ui
