.gitignore
springwolf-core/src/test/java/io/github/stavshamir/springwolf/schemas/DefaultSchemasServiceTest.java
springwolf-core/src/test/resources/schemas/documented-definitions.json
springwolf-examples/springwolf-amqp-example/build.gradle
springwolf-examples/springwolf-amqp-example/src/main/java/io/github/stavshamir/springwolf/example/dtos/AnotherPayloadDto.java
springwolf-examples/springwolf-amqp-example/src/main/java/io/github/stavshamir/springwolf/example/dtos/ExamplePayloadDto.java

Added documentation examples that can be referenced in the PR for this issue [springwolf/springwolf.github.io/#5](https://github.com/springwolf/springwolf.github.io/issues/5)
relates to #35

Added example of message payload documentation

---

springwolf-add-ons/springwolf-common-model-converters/README.md
springwolf-add-ons/springwolf-common-model-converters/build.gradle

Change the moneta dependency to the actual core jar and not the moneta pom.

fix moneta dependency

---

springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/components/ComponentComponentsScannerTest.java
springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/components/TestBeanConditional.java

test should be modified to specify profile

Tests that should work when conditions based on profiles be supported

---

springwolf-examples/springwolf-kafka-example/src/main/java/io/github/stavshamir/springwolf/example/configuration/AsyncApiConfiguration.java
springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.json

Relates to https://github.com/springwolf/springwolf-ui/pull/5

docs: Use kafka specific async api title

---

springwolf-core/build.gradle

Co-authored-by: Timon Back <timonback@users.noreply.github.com>

chore: bump jackson-databind version from 2.9.4 to 2.9.10.8

---

springwolf-core/build.gradle
springwolf-core/src/test/java/io/github/stavshamir/springwolf/schemas/DefaultSchemasServiceTest.java
springwolf-core/src/test/resources/schemas/definitions.json

Co-authored-by: Timon Back <timonback@users.noreply.github.com>

chore: bump swagger-reflector version from 2.0.5 to 2.0.8

---

springwolf-core/build.gradle
springwolf-examples/springwolf-amqp-example/build.gradle
springwolf-examples/springwolf-kafka-example/build.gradle
springwolf-plugins/springwolf-amqp-plugin/build.gradle
springwolf-plugins/springwolf-kafka-plugin/build.gradle

Co-authored-by: Timon Back <timonback@users.noreply.github.com>

chore: bump guava version from 27.0.1 to 31.1

---

springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/SpringPayloadAnnotationTypeExtractor.java
springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/SpringPayloadAnnotationTypeExtractorTest.java

Add log message to indicate mismatch java versions
Co-Authored-By: 93372330+sam0r040@users.noreply.github.com

test: GH-132: Add test for SpringPayloadAnnotationTypeExtractor

---

.github/workflows/publish-releases.yml
RELEASING.md
springwolf-add-ons/springwolf-common-model-converters/build.gradle
springwolf-core/build.gradle
springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/channel/operation/message/Message.java
springwolf-core/src/test/resources/asyncapi/asyncapi.json
springwolf-examples/springwolf-amqp-example/build.gradle
springwolf-examples/springwolf-amqp-example/docker-compose.yml
springwolf-examples/springwolf-amqp-example/src/test/resources/asyncapi.json
springwolf-examples/springwolf-cloud-stream-example/build.gradle
springwolf-examples/springwolf-cloud-stream-example/docker-compose.yml
springwolf-examples/springwolf-cloud-stream-example/src/test/resources/asyncapi.json
springwolf-examples/springwolf-kafka-example/build.gradle
springwolf-examples/springwolf-kafka-example/docker-compose.yml
springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.json
springwolf-plugins/springwolf-amqp-plugin/README.md
springwolf-plugins/springwolf-amqp-plugin/build.gradle
springwolf-plugins/springwolf-cloud-stream-plugin/build.gradle
springwolf-plugins/springwolf-kafka-plugin/README.md
springwolf-plugins/springwolf-kafka-plugin/build.gradle

- Add schemaFormat to doc (relates to #160)
- Add release guide to repository
- Update version for release
- Automate tagging of the release
- smaller updates

Preparing upcoming release

---

springwolf-examples/springwolf-kafka-example/build.gradle
springwolf-examples/springwolf-kafka-example/src/main/java/io/github/stavshamir/springwolf/example/configuration/CustomWebSecurityConfigurerAdapter.java

Relates to https://github.com/springwolf/springwolf.github.io/issues/3

feat: Demonstrate usage of springwolf-kafka-example with spring-security

---

springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/channel/operation/message/bindings/EmptyMessageBinding.java
springwolf-examples/springwolf-cloud-stream-example/src/test/resources/asyncapi.json
springwolf-plugins/springwolf-cloud-stream-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/cloudstream/CloudStreamFunctionChannelsScanner.java
springwolf-plugins/springwolf-cloud-stream-plugin/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/cloudstream/CloudStreamFunctionChannelsScannerTest.java

Resolves https://github.com/springwolf/springwolf-core/issues/171

bugfix: Add messagebinding in CloudStreamFunctionChannelsScanner

---

.github/workflows/publish-releases.yml
.github/workflows/springwolf-amqp.yml
.github/workflows/springwolf-cloud-stream.yml
.github/workflows/springwolf-kafka.yml
springwolf-examples/springwolf-amqp-example/build.gradle
springwolf-examples/springwolf-cloud-stream-example/build.gradle
springwolf-examples/springwolf-kafka-example/build.gradle

Preparing the release of the docker images
Requires new 2 secrets within github settings:
- DOCKERHUB_USERNAME
- DOCKERHUB_TOKEN

Publish docker image

---

springwolf-ui/build.gradle
springwolf-ui/package-lock.json
springwolf-ui/package.json

Resolves: https://github.com/springwolf/springwolf-core/pull/237

chore(deps): Bump to node 18.16.1

---

springwolf-add-ons/springwolf-common-model-converters/build.gradle
springwolf-core/build.gradle
springwolf-examples/springwolf-amqp-example/build.gradle
springwolf-examples/springwolf-amqp-example/docker-compose.yml
springwolf-examples/springwolf-cloud-stream-example/build.gradle
springwolf-examples/springwolf-cloud-stream-example/docker-compose.yml
springwolf-examples/springwolf-kafka-example/build.gradle
springwolf-examples/springwolf-kafka-example/docker-compose.yml
springwolf-plugins/springwolf-amqp-plugin/README.md
springwolf-plugins/springwolf-amqp-plugin/build.gradle
springwolf-plugins/springwolf-cloud-stream-plugin/build.gradle
springwolf-plugins/springwolf-kafka-plugin/README.md
springwolf-plugins/springwolf-kafka-plugin/build.gradle
springwolf-ui/README.md
springwolf-ui/build.gradle

Apply version strategy from GH-258

chore: GH-258: Update version to 0.13.0

---

dependencies.gradle
springwolf-add-ons/springwolf-common-model-converters/build.gradle
springwolf-core/build.gradle
springwolf-examples/springwolf-amqp-example/build.gradle
springwolf-examples/springwolf-cloud-stream-example/build.gradle
springwolf-examples/springwolf-kafka-example/build.gradle
springwolf-plugins/springwolf-amqp-plugin/build.gradle
springwolf-plugins/springwolf-kafka-plugin/build.gradle

Re-apply rules introduced in 159c54c7fa743d680938e67ffb6a224e4df8db6b
CC: @harare

chore: Common naming of dependencies

---

springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/classes/AbstractAnnotatedClassScanner.java
springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/classes/ComponentClassScanner.java
springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/classes/ConfigurationClassScanner.java
springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/classes/ComponentClassScannerIntegrationTest.java
springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/classes/TestConditionalComponent.java
springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/classes/TestOtherConditionalComponent.java

Added Environment to the AbstractAnnotatedClassScanner
Instantiate ClassPathScanningCandidateComponentProvider with environment, if available.
Updated tests to add scenario where Environment properties should trigger inclusion of Conditional Component

Support @Conditional: Add environment to AbstractAnnotatedClassScanner

---

build.gradle
springwolf-add-ons/springwolf-common-model-converters/build.gradle
springwolf-core/build.gradle
springwolf-examples/springwolf-amqp-example/build.gradle
springwolf-examples/springwolf-cloud-stream-example/build.gradle
springwolf-examples/springwolf-kafka-example/build.gradle
springwolf-examples/springwolf-sqs-example/build.gradle
springwolf-plugins/springwolf-amqp-plugin/build.gradle
springwolf-plugins/springwolf-cloud-stream-plugin/build.gradle
springwolf-plugins/springwolf-kafka-plugin/build.gradle
springwolf-plugins/springwolf-sqs-plugin/build.gradle

Removed Spotless configuration duplicity across the different modules

Unify spotless

---

springwolf-examples/springwolf-sqs-example/src/test/resources/asyncapi.json
springwolf-plugins/springwolf-sqs-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/SqsMessageBindingProcessor.java

Allows publishing sqs messages from springwolf-ui when using `@AsyncListener` and `@AsyncPublisher`

fix(sqs): add SqsMessageBindingProcessor

---

dependencies.gradle
springwolf-examples/springwolf-cloud-stream-example/build.gradle
springwolf-examples/springwolf-kafka-example/build.gradle
springwolf-plugins/springwolf-cloud-stream-plugin/build.gradle
springwolf-plugins/springwolf-kafka-plugin/build.gradle

Revert "chore(deps): Bump snakeyaml and kafka" (#384)

---

springwolf-core/src/main/java/io/github/stavshamir/springwolf/SpringwolfAutoConfiguration.java
springwolf-core/src/main/java/io/github/stavshamir/springwolf/SpringwolfScannerConfiguration.java
springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/amqp/SpringwolfAmqpAutoConfiguration.java
springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/amqp/SpringwolfAmqpProducerConfiguration.java
springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/amqp/SpringwolfAmqpScannerConfiguration.java
springwolf-plugins/springwolf-cloud-stream-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/cloudstream/SpringwolfCloudStreamAutoConfiguration.java
springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/kafka/SpringwolfKafkaAutoConfiguration.java
springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/kafka/SpringwolfKafkaScannerConfiguration.java
springwolf-plugins/springwolf-sns-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/sns/SpringwolfSnsAutoConfiguration.java
springwolf-plugins/springwolf-sqs-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/sqs/SpringwolfSqsAutoConfiguration.java
springwolf-plugins/springwolf-sqs-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/sqs/SpringwolfSqsProducerConfiguration.java
springwolf-plugins/springwolf-sqs-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/sqs/SpringwolfSqsScannerConfiguration.java

Rename SpringwolfSqsWebConfiguration to SpringwolfSqsProducerConfiguration Extract SpringwolfAmqpProducerConfiguration

chore: add havingValue to auto configurations

---

springwolf-examples/springwolf-sqs-example/src/test/java/io/github/stavshamir/springwolf/example/sqs/ApiIntegrationTest.java
springwolf-examples/springwolf-sqs-example/src/test/resources/asyncapi.json
springwolf-plugins/springwolf-sqs-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/bindings/processor/SqsMessageBindingProcessor.java

The `SqsMessageBindingProcessor` was wrongly using the `AMQPMessageBinding` instead of `SQSMessageBinding`.

fix: Minor fix with SQS Message Binding

---

springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/AbstractClassLevelListenerScanner.java
springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/AbstractMethodLevelListenerScanner.java
springwolf-examples/springwolf-amqp-example/src/main/java/io/github/stavshamir/springwolf/example/amqp/configuration/RabbitConfiguration.java
springwolf-examples/springwolf-amqp-example/src/main/java/io/github/stavshamir/springwolf/example/amqp/consumers/ExampleConsumer.java
springwolf-examples/springwolf-amqp-example/src/test/resources/asyncapi.json
springwolf-examples/springwolf-amqp-example/src/test/resources/asyncapi_withdocketfromenvironment.json
springwolf-plugins/springwolf-amqp-plugin/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/ClassLevelRabbitListenerScannerIntegrationTest.java
springwolf-plugins/springwolf-amqp-plugin/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/MethodLevelRabbitListenerScannerIntegrationTest.java
springwolf-plugins/springwolf-kafka-plugin/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/ClassLevelKafkaListenerScannerIntegrationTest.java
springwolf-plugins/springwolf-kafka-plugin/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/MethodLevelKafkaListenerScannerIntegrationTest.java
springwolf-plugins/springwolf-sqs-plugin/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/MethodLevelSqsListenerScannerIntegrationTest.java

Addresses: https://github.com/springwolf/springwolf-core/issues/446

feat(core): handle multiple payloads in methodLevelListener

---

springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncOperation.java
springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/payload/AsyncApiPayload.java
springwolf-core/src/main/java/io/github/stavshamir/springwolf/schemas/DefaultSchemasService.java
springwolf-core/src/test/java/io/github/stavshamir/springwolf/schemas/DefaultSchemasServiceTest.java
springwolf-core/src/test/resources/schemas/api-payload.json
springwolf-examples/springwolf-amqp-example/src/test/java/io/github/stavshamir/springwolf/example/amqp/ApiIntegrationTest.java
springwolf-examples/springwolf-kafka-example/src/main/java/io/github/stavshamir/springwolf/example/kafka/consumers/ExampleClassLevelKafkaListener.java
springwolf-examples/springwolf-kafka-example/src/main/java/io/github/stavshamir/springwolf/example/kafka/consumers/StringConsumer.java
springwolf-examples/springwolf-kafka-example/src/test/java/io/github/stavshamir/springwolf/example/kafka/SpringContextIntegrationTest.java
springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.json

Relates to https://github.com/springwolf/springwolf-core/issues/377

Feat/allow to document primitive data types (GH-377)

---

.github/workflows/springwolf-plugins.yml

Spectral rules are limited and benefit is too low

chore: remove spectral linting in gh action

---

springwolf-asyncapi/src/test/java/io/github/stavshamir/springwolf/asyncapi/v3/bindings/amqp/AMQPBindingTest.java
springwolf-asyncapi/src/test/resources/v3/bindings/amqp/amqp-channel-queue.yaml
springwolf-asyncapi/src/test/resources/v3/bindings/amqp/amqp-channel-routing.yaml
springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/AsyncAnnotationChannelsScannerTest.java
springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/ClassLevelAnnotationChannelsScannerTest.java
springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/MethodLevelAnnotationChannelsScannerIntegrationTest.java
springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/MethodLevelAnnotationChannelsScannerTest.java
springwolf-examples/springwolf-amqp-example/src/test/resources/asyncapi.json
springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/bindings/processor/AmqpMessageBindingProcessor.java
springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/RabbitListenerUtil.java
springwolf-plugins/springwolf-amqp-plugin/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/bindings/processor/AmqpOperationBindingProcessorTest.java
springwolf-plugins/springwolf-amqp-plugin/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/RabbitListenerUtilTest.java

Continue with the fixes. The code is feature ready, but still some bugs require fixing.

fix: Fixed core tests

---

springwolf-core/src/main/java/io/github/stavshamir/springwolf/SpringwolfAutoConfiguration.java
springwolf-core/src/main/java/io/github/stavshamir/springwolf/SpringwolfScannerConfiguration.java
springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/AbstractOperationDataScanner.java
springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/ConsumerOperationDataScanner.java
springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/ProducerOperationDataScanner.java
springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/channel/operation/message/header/AsyncHeadersForCloudEventsBuilder.java
springwolf-core/src/main/java/io/github/stavshamir/springwolf/configuration/AsyncApiDocket.java
springwolf-core/src/main/java/io/github/stavshamir/springwolf/configuration/DefaultAsyncApiDocketService.java
springwolf-core/src/main/java/io/github/stavshamir/springwolf/configuration/properties/SpringwolfConfigProperties.java
springwolf-core/src/test/java/io/github/stavshamir/springwolf/CustomBeanAsyncApiDocketConfiguration.java
springwolf-core/src/test/java/io/github/stavshamir/springwolf/SpringContextIntegrationTest.java
springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/DefaultAsyncApiServiceIntegrationTest.java
springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/ConsumerOperationDataScannerIntegrationTest.java
springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/ProducerOperationDataScannerIntegrationTest.java
springwolf-core/src/test/java/io/github/stavshamir/springwolf/configuration/DefaultAsyncApiDocketServiceIntegrationTest.java
springwolf-core/src/test/java/io/github/stavshamir/springwolf/configuration/DefaultAsyncApiDocketServiceTest.java
springwolf-core/src/test/java/io/github/stavshamir/springwolf/integrationtests/AutoConfigurationIntegrationTest.java
springwolf-core/src/test/java/io/github/stavshamir/springwolf/integrationtests/InitModeIntegrationTest.java
springwolf-core/src/test/java/io/github/stavshamir/springwolf/integrationtests/TestApplication.java
springwolf-plugins/springwolf-amqp-plugin/README.md
springwolf-plugins/springwolf-cloud-stream-plugin/build.gradle
springwolf-plugins/springwolf-cloud-stream-plugin/src/test/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/cloudstream/CloudStreamFunctionChannelsScannerIntegrationTest.java
springwolf-plugins/springwolf-kafka-plugin/README.md

This reverts commit c4ea459aa5cf346c70937445cada4bd8d14140ba.

Revert "chore: remove deprecated asyncapidocket bean (#524)"

---

springwolf-add-ons/springwolf-common-model-converters/src/main/java/io/github/stavshamir/springwolf/addons/common_model_converters/converters/monetaryamount/MonetaryAmount.java
springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.json
springwolf-ui/src/app/app.module.ts
springwolf-ui/src/app/components/schemas/range/schema-range.component.css
springwolf-ui/src/app/components/schemas/range/schema-range.component.html
springwolf-ui/src/app/components/schemas/range/schema-range.component.ts
springwolf-ui/src/app/components/schemas/schema/schema.component.css
springwolf-ui/src/app/components/schemas/schema/schema.component.html
springwolf-ui/src/app/models/schema.model.ts
springwolf-ui/src/app/service/asyncapi/asyncapi-mapper.service.ts
springwolf-ui/src/app/service/asyncapi/models/schema.model.ts

**Describe the feature request**
Support exclusiveMinimum and exclusiveMaximum in UI.
Resolves #378

Support exclusiveMinimum and exclusiveMaximum

---

.github/workflows/owasp.yml
.github/workflows/publish-releases.yml
.github/workflows/springwolf-addons.yml
.github/workflows/springwolf-asyncapi.yml
.github/workflows/springwolf-core.yml
.github/workflows/springwolf-plugins.yml
.github/workflows/springwolf-ui.yml

chore(gh): replace gradle/gradle-build-action with superceding gradle/actions/setup-gradle action

---

springwolf-add-ons/springwolf-common-model-converters/src/main/java/io/github/stavshamir/springwolf/addons/common_model_converters/converters/monetaryamount/MonetaryAmount.java
springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/DefaultAsyncApiSerializerService.java
springwolf-core/src/main/java/io/github/stavshamir/springwolf/schemas/postprocessor/SwaggerSchemaPostProcessor.java
springwolf-core/src/test/java/io/github/stavshamir/springwolf/asyncapi/DefaultAsyncApiSerializerServiceIntegrationTest.java
springwolf-core/src/test/java/io/github/stavshamir/springwolf/schemas/postprocessor/SwaggerSchemaPostProcessorTest.java
springwolf-core/src/test/resources/asyncapi/asyncapi.json
springwolf-core/src/test/resources/asyncapi/asyncapi.yaml
springwolf-examples/springwolf-amqp-example/src/test/resources/asyncapi.json
springwolf-examples/springwolf-cloud-stream-example/src/test/resources/asyncapi.json
springwolf-examples/springwolf-jms-example/src/test/resources/asyncapi.json
springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.json
springwolf-examples/springwolf-sns-example/src/test/resources/asyncapi.json
springwolf-examples/springwolf-sqs-example/src/test/resources/asyncapi.json
springwolf-ui/src/app/service/asyncapi/asyncapi-mapper.service.ts
springwolf-ui/src/app/service/asyncapi/models/schema.model.ts

Swagger generates OpenApi schemas which are not 100% compatible to AsyncApi

fix: handle AsyncApi v3 maximumValue field

---

springwolf-ui/jest.config.js
springwolf-ui/package-lock.json
springwolf-ui/package.json
springwolf-ui/src/app/service/asyncapi/asyncapi-mapper.service.spec.ts
springwolf-ui/src/app/service/mock/example-data.ts
springwolf-ui/src/app/service/mock/mock-server.ts

test: Validate asyncapi.json using asyncapi/parser

---

springwolf-ui/README.md
springwolf-ui/package.json
springwolf-ui/src/app/components/channels/channel-main/channel-main.component.html
springwolf-ui/src/app/components/json/json.component.ts

fix(ui): display channel headers as json example

---

springwolf-ui/src/app/service/mock/example-data.ts
springwolf-ui/src/app/service/mock/mock-server.ts
springwolf-ui/tsconfig.json

fix(springwolf-ui): render original AsyncAPI in ui

---

springwolf-asyncapi/src/main/java/io/github/springwolf/asyncapi/v3/model/channel/ServerReference.java
springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/channels/AsyncAnnotationChannelsScanner.java
springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/channels/annotations/AsyncAnnotationChannelsScannerTest.java
springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/operations/annotations/AsyncAnnotationOperationsScannerTest.java
springwolf-examples/springwolf-kafka-example/src/main/java/io/github/springwolf/examples/kafka/producers/NestedProducer.java
springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.json

Closes #639 
Removes also unused variables in test

fix(core): create correct servers reference

---

gradle/wrapper/gradle-wrapper.properties
gradlew.bat

Upgraded to the latest Gradle stable version.
See https://docs.gradle.org/8.7/release-notes.html

chore: Upgrade to Gradle 8.7

---

build.gradle
springwolf-add-ons/springwolf-common-model-converters/build.gradle
springwolf-add-ons/springwolf-kotlinx-serialization-model-converter/build.gradle
springwolf-asyncapi/build.gradle
springwolf-core/build.gradle
springwolf-examples/springwolf-amqp-example/build.gradle
springwolf-examples/springwolf-cloud-stream-example/build.gradle
springwolf-examples/springwolf-jms-example/build.gradle
springwolf-examples/springwolf-kafka-example/build.gradle
springwolf-examples/springwolf-sns-example/build.gradle
springwolf-examples/springwolf-sqs-example/build.gradle
springwolf-plugins/springwolf-kafka-plugin/build.gradle

Minor fixes, dependency alignments and removal of deprecated options

chore: Minor Gradle tweaks

---

springwolf-examples/springwolf-kafka-example/src/main/java/io/github/springwolf/examples/kafka/consumers/ExampleConsumer.java
springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/springwolf/plugins/kafka/asyncapi/scanners/common/KafkaListenerUtil.java
springwolf-plugins/springwolf-kafka-plugin/src/test/java/io/github/springwolf/plugins/kafka/asyncapi/scanners/common/KafkaListenerUtilTest.java

relates to https://github.com/springwolf/springwolf-core/issues/739

feat(kafka): support KafkaListener topicPattern parameter

---

springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/common/payload/TypeToClassConverter.java
springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/common/payload/TypeToClassConverterTest.java
springwolf-examples/springwolf-kafka-example/src/main/resources/application.properties

Relates to https://github.com/springwolf/springwolf-core/issues/729

fix(core): extract payload in generics from correct index

---

springwolf-core/src/main/java/io/github/springwolf/core/controller/PublishingPayloadCreator.java
springwolf-core/src/main/java/io/github/springwolf/core/controller/dtos/MessageDto.java
springwolf-core/src/test/java/io/github/springwolf/core/controller/PublishingPayloadCreatorTest.java

fixes https://github.com/springwolf/springwolf-core/issues/752

feat(core): allow publishing of all data types

---

springwolf-core/build.gradle
springwolf-core/src/main/java/io/github/springwolf/core/configuration/SpringwolfUiResourceConfiguration.java
springwolf-core/src/main/java/io/github/springwolf/core/configuration/SpringwolfUiResourceConfigurer.java
springwolf-core/src/main/java/io/github/springwolf/core/configuration/SpringwolfWebConfiguration.java
springwolf-core/src/main/java/io/github/springwolf/core/configuration/properties/SpringwolfConfigProperties.java
springwolf-core/src/main/java/io/github/springwolf/core/controller/AsyncApiController.java
springwolf-examples/springwolf-sqs-example/src/test/java/io/github/springwolf/examples/sqs/CustomPathConfigurationIntegrationTest.java
springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/springwolf/plugins/amqp/controller/SpringwolfAmqpController.java
springwolf-plugins/springwolf-jms-plugin/src/main/java/io/github/springwolf/plugins/jms/controller/SpringwolfJmsController.java
springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/springwolf/plugins/kafka/controller/SpringwolfKafkaController.java
springwolf-plugins/springwolf-sns-plugin/src/main/java/io/github/springwolf/plugins/sns/controller/SpringwolfSnsController.java
springwolf-plugins/springwolf-sqs-plugin/src/main/java/io/github/springwolf/plugins/sqs/controller/SpringwolfSqsController.java

Aims to implement https://github.com/springwolf/springwolf-core/issues/757

feat(core): make springwolf ui path configurable

---

README.md

CC: https://github.com/pcomp96

docs: Add alten italia as springwolf user

---

springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/common/payload/TypeToClassConverter.java
springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/common/payload/TypeToClassConverterTest.java

Relates to https://github.com/springwolf/springwolf-core/issues/792

fix: Handle class types with extends and primitive types like byte[]

---

springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/components/examples/walkers/DefaultSchemaWalker.java
springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/components/DefaultJsonComponentsServiceTest.java

relates to https://github.com/springwolf/springwolf-core/issues/782

fix(core): handle recursion in allOf schema

---

springwolf-add-ons/springwolf-kotlinx-serialization-model-converter/src/main/java/io/github/springwolf/addons/kotlinx_serialization_model_converter/configuration/KotlinxSerializationModelConverterAutoConfiguration.java
springwolf-core/src/main/java/io/github/springwolf/core/configuration/SpringwolfAutoConfiguration.java
springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/springwolf/plugins/amqp/configuration/SpringwolfAmqpScannerConfiguration.java
springwolf-plugins/springwolf-jms-plugin/src/main/java/io/github/springwolf/plugins/jms/configuration/SpringwolfJmsScannerConfiguration.java
springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/springwolf/plugins/kafka/configuration/SpringwolfKafkaScannerConfiguration.java
springwolf-plugins/springwolf-sqs-plugin/src/main/java/io/github/springwolf/plugins/sqs/configuration/SpringwolfSqsScannerConfiguration.java
springwolf-plugins/springwolf-stomp-plugin/src/main/java/io/github/springwolf/plugins/stomp/configuration/SpringwolfStompScannerConfiguration.java

Optimazation for upcoming Spring bean injection fast pass based on bean names

chore: align bean with actual class names

---

springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/common/utils/AsyncAnnotationUtil.java
springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/common/utils/AsyncAnnotationUtilTest.java

feat(core): add validation for schema name in AsyncOperation.Headers

---

springwolf-ui/src/app/components/header/header.component.html
springwolf-ui/src/app/components/header/header.component.spec.ts
springwolf-ui/src/app/components/header/header.component.ts
springwolf-ui/src/app/components/new/channels/channel-main/channel-operation.component.html
springwolf-ui/src/app/components/new/channels/channel-main/channel-operation.component.ts
springwolf-ui/src/app/material.module.ts
springwolf-ui/src/app/service/ui.service.ts

Relates to https://github.com/springwolf/springwolf-core/issues/872

feat(ui): Allow to hide bindings

---

springwolf-examples/springwolf-amqp-example/src/main/java/io/github/springwolf/examples/amqp/dtos/AnotherPayloadDto.java
springwolf-examples/springwolf-amqp-example/src/main/java/io/github/springwolf/examples/amqp/dtos/ExamplePayloadDto.java
springwolf-examples/springwolf-amqp-example/src/test/resources/asyncapi.json
springwolf-examples/springwolf-cloud-stream-example/src/main/java/io/github/springwolf/examples/cloudstream/dtos/AnotherPayloadDto.java
springwolf-examples/springwolf-cloud-stream-example/src/main/java/io/github/springwolf/examples/cloudstream/dtos/ExamplePayloadDto.java
springwolf-examples/springwolf-cloud-stream-example/src/main/java/io/github/springwolf/examples/cloudstream/dtos/GooglePubSubPayloadDto.java
springwolf-examples/springwolf-cloud-stream-example/src/test/resources/asyncapi.json
springwolf-examples/springwolf-jms-example/src/main/java/io/github/springwolf/examples/jms/dtos/AnotherPayloadDto.java
springwolf-examples/springwolf-jms-example/src/main/java/io/github/springwolf/examples/jms/dtos/ExamplePayloadDto.java
springwolf-examples/springwolf-jms-example/src/test/resources/asyncapi.json
springwolf-examples/springwolf-kafka-example/src/main/java/io/github/springwolf/examples/kafka/dtos/AnotherPayloadDto.java
springwolf-examples/springwolf-kafka-example/src/main/java/io/github/springwolf/examples/kafka/dtos/ExamplePayloadDto.java
springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.json
springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.yaml
springwolf-examples/springwolf-sns-example/src/main/java/io/github/springwolf/examples/sns/dtos/AnotherPayloadDto.java
springwolf-examples/springwolf-sns-example/src/main/java/io/github/springwolf/examples/sns/dtos/ExamplePayloadDto.java
springwolf-examples/springwolf-sns-example/src/test/resources/asyncapi.json
springwolf-examples/springwolf-sqs-example/src/main/java/io/github/springwolf/examples/sqs/dtos/AnotherPayloadDto.java
springwolf-examples/springwolf-sqs-example/src/main/java/io/github/springwolf/examples/sqs/dtos/ExamplePayloadDto.java
springwolf-examples/springwolf-sqs-example/src/test/resources/asyncapi.json
springwolf-examples/springwolf-stomp-example/src/main/java/io/github/springwolf/examples/stomp/stomp/dtos/AnotherPayloadDto.java
springwolf-examples/springwolf-stomp-example/src/main/java/io/github/springwolf/examples/stomp/stomp/dtos/ExamplePayloadDto.java
springwolf-examples/springwolf-stomp-example/src/test/resources/asyncapi.json

Better demonstrate the capabilities of the swagger Schema annotation

chore(example): use maxLength and maximum value

---

springwolf-examples/springwolf-cloud-stream-example/docker-compose.yml
springwolf-examples/springwolf-kafka-example/docker-compose.yml

Version is chosen randomly as the current cp-kafka:latest is not woring anymore

chore(kafka): hardcode cp-kafka

---

springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/common/payload/internal/PayloadClassExtractor.java
springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/common/payload/internal/TypeToClassConverter.java
springwolf-core/src/main/java/io/github/springwolf/core/configuration/SpringwolfAutoConfiguration.java
springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/common/payload/internal/PayloadClassExtractorTest.java
springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/scanners/common/payload/internal/TypeToClassConverterTest.java
springwolf-examples/springwolf-cloud-stream-example/src/main/resources/application.properties
springwolf-examples/springwolf-cloud-stream-example/src/test/resources/asyncapi.json
springwolf-plugins/springwolf-cloud-stream-plugin/src/main/java/io/github/springwolf/plugins/cloudstream/asyncapi/scanners/channels/CloudStreamFunctionChannelsScanner.java
springwolf-plugins/springwolf-cloud-stream-plugin/src/main/java/io/github/springwolf/plugins/cloudstream/asyncapi/scanners/common/FunctionalChannelBeanBuilder.java
springwolf-plugins/springwolf-cloud-stream-plugin/src/main/java/io/github/springwolf/plugins/cloudstream/asyncapi/scanners/common/FunctionalChannelBeanData.java
springwolf-plugins/springwolf-cloud-stream-plugin/src/main/java/io/github/springwolf/plugins/cloudstream/asyncapi/scanners/operations/CloudStreamFunctionOperationsScanner.java
springwolf-plugins/springwolf-cloud-stream-plugin/src/test/java/io/github/springwolf/plugins/cloudstream/asyncapi/scanners/channels/CloudStreamFunctionChannelsScannerIntegrationTest.java

Left over task for issue #891 . Refactor cloudStream functionality

refactor cloudStream functionality

---

springwolf-ui/src/app/components/sidenav/sidenav.component.ts

Based on https://github.com/springwolf/springwolf-core/security/code-scanning/143

fix(ui): use less permissive regex

---

gradle/libs.versions.toml

Relates to https://github.com/springwolf/springwolf-core/issues/1086

Fix gradle version catalog for maven

---

springwolf-add-ons/springwolf-generic-binding/src/main/java/io/github/springwolf/addons/generic_binding/annotation/configuration/SpringwolfGenericBindingAutoConfiguration.java
springwolf-core/src/main/java/io/github/springwolf/core/configuration/SpringwolfAutoConfiguration.java
springwolf-core/src/main/java/io/github/springwolf/core/configuration/SpringwolfScannerConfiguration.java
springwolf-plugins/springwolf-amqp-plugin/src/main/java/io/github/springwolf/plugins/amqp/configuration/SpringwolfAmqpScannerConfiguration.java
springwolf-plugins/springwolf-cloud-stream-plugin/src/main/java/io/github/springwolf/plugins/cloudstream/configuration/SpringwolfCloudStreamAutoConfiguration.java
springwolf-plugins/springwolf-jms-plugin/src/main/java/io/github/springwolf/plugins/jms/configuration/SpringwolfJmsScannerConfiguration.java
springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/springwolf/plugins/kafka/configuration/SpringwolfKafkaScannerConfiguration.java
springwolf-plugins/springwolf-sqs-plugin/src/main/java/io/github/springwolf/plugins/sqs/configuration/SpringwolfSqsScannerConfiguration.java
springwolf-plugins/springwolf-stomp-plugin/src/main/java/io/github/springwolf/plugins/stomp/configuration/SpringwolfStompScannerConfiguration.java

Follow up to https://github.com/springwolf/springwolf-core/issues/1180

chore: Add ConditionalOnMissingBean to all beans

---

springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/grouping/GroupingService.java
springwolf-core/src/test/java/io/github/springwolf/core/asyncapi/grouping/GroupingServiceTest.java
springwolf-examples/springwolf-kafka-example/src/test/resources/groups/vehicles.json
springwolf-ui/src/app/service/asyncapi/asyncapi-mapper.service.spec.ts

Relates to https://github.com/springwolf/springwolf-core/issues/1191

fix(core): resolve referenced schemas in grouping

---

build.gradle

Based on https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/#overview

chore: publish to central sonatype

---

springwolf-core/src/main/java/io/github/springwolf/core/configuration/SpringwolfUiResourceConfigurer.java
springwolf-core/src/main/java/io/github/springwolf/core/configuration/properties/SpringwolfConfigProperties.java

The resourceHandler is additive.
SpringwolfUiResourceConfigurer allows to run springwolf-ui when the base-path is non-default

bugfix(ui): only add ressource handler for custom springwolf paths
